### ISSUE TITLE
Improve efficiency of datasets associated providers

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#101]
The issue is motivated by the situation that is present in the Hetor project, that exacerbates a known scalability problem about the pre-loading of dataset names and metadata of associated  providers.

**Comment by vitsca** [comment]
The (2 step) solution has already been discussed in the team: make only the dataset names pre-loaded, and load on demand the metadata (or) make loading asynchronous with only the first dataset name/metadata preloaded. 
It requires some intervention on the controllet and on the server (we should re-use the CKAN service that provides the metadata)

**Comment by rended** [comment]
Now the cache system is improved and largely support Hetor. The Controllet interface is changed to support dataset/resources views.
