### ISSUE TITLE
[Cocreation] Close button in "All datasets" dialog

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#102]
In "All datasets" dialog is missing close button:

![image](https://cloud.githubusercontent.com/assets/22379520/19727739/f5d3bd64-9b90-11e6-980a-9af1fb6499dc.png)

**Comment by luigser** [comment]
"All dataset" is a page. it's no possible to close but it is possible to open a new page(SPOD feature) by clicking on related link. Should we increase the size of the table to fit the screen?
