### ISSUE TITLE
Agora: error filling out the login dialog for user not connected

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#105]
Try with following  url:
http://prato.routetopa.eu/public-room/#!/31:

see screenshot:
![image](https://cloud.githubusercontent.com/assets/22379520/20189541/e9de909e-a77d-11e6-993a-e5be7cbb6a32.png)

after login , an user is connected, first the following window appears:
![image](https://cloud.githubusercontent.com/assets/22379520/20189574/17cb198c-a77e-11e6-8c02-e1373aab2c37.png)

**Comment by lucavicidomini** [comment]
Fixed by commit routetopa/spod-plugin-agora@1003d8222f2b5fbf2043e87a32eb93b96cf6f29a
