### ISSUE TITLE
Prato: Italian version

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#108]
List of strings in Cocreation: 
1)
![image](https://cloud.githubusercontent.com/assets/22379520/20214211/fffe3a84-a80c-11e6-9b09-c49fb6ec012f.png)

2) cocreation+room_confirm_to_join 

3) delete a cocreation data
![image](https://cloud.githubusercontent.com/assets/22379520/20215754/c05d0fc2-a816-11e6-96a4-6c18b077d4e7.png)

4)
![image](https://cloud.githubusercontent.com/assets/22379520/20248732/528dfcd8-a9ea-11e6-8323-bfa6432bd9e7.png)

5)Add a datalet (+)
![image](https://cloud.githubusercontent.com/assets/22379520/20249313/5ea93854-a9f7-11e6-9f89-4a7185c44464.png)

**Comment by vitsca** [comment]
Other strings to change in the co-creation data room dialogue.. 
In the date, both the date picker is in english and the "From" "To" labels.. as shown below

<img width="481" alt="schermata 2016-11-13 alle 21 42 53" src="https://cloud.githubusercontent.com/assets/2544302/20248753/fa2b8a50-a9ea-11e6-896a-3f6f0bcaddaf.png">
<img width="858" alt="schermata 2016-11-13 alle 21 43 40" src="https://cloud.githubusercontent.com/assets/2544302/20248755/fa64165e-a9ea-11e6-88b2-d1234a91877a.png">
<img width="858" alt="schermata 2016-11-13 alle 21 43 50" src="https://cloud.githubusercontent.com/assets/2544302/20248754/fa60472c-a9ea-11e6-9158-8322c3a0c356.png">
<img width="377" alt="schermata 2016-11-13 alle 21 44 16" src="https://cloud.githubusercontent.com/assets/2544302/20248756/fa67b250-a9ea-11e6-861b-4aeb46fdfcbb.png">

**Comment by vitsca** [comment]
Another string to translate: the notification in the data cocreation room as shown
<img width="427" alt="schermata 2016-11-13 alle 21 51 48" src="https://cloud.githubusercontent.com/assets/2544302/20248781/759d0cea-a9eb-11e6-8c72-1d552218c774.png">

**Comment by vitsca** [comment]
The controllet (called from the cocreation data) in the third step shows the description of the graphs in english.. (didn't we have the italian version?) 
<img width="643" alt="schermata 2016-11-13 alle 21 53 18" src="https://cloud.githubusercontent.com/assets/2544302/20248789/af96aed8-a9eb-11e6-90fb-bbe2bbfa5660.png">

**Comment by vitsca** [comment]
In the info of the cocreation room, we have several errors
"Gol" (That in english is NOT correct should be Goal!) is to be "Obiettivo"
"Members"
"Joined" "Owner"
<img width="670" alt="schermata 2016-11-13 alle 21 56 10" src="https://cloud.githubusercontent.com/assets/2544302/20248825/27bc9b0c-a9ec-11e6-818a-e38f7f4f524d.png">

**Comment by pinapalmieri** [comment]
Add datalet is only english version:

![image](https://cloud.githubusercontent.com/assets/22379520/20249284/89a097ce-a9f6-11e6-97c6-c5069d973ecf.png)

**Comment by pinapalmieri** [comment]
![image](https://cloud.githubusercontent.com/assets/22379520/20516797/8241a22c-b098-11e6-93c9-0f4a9060f135.png)

**Comment by pinapalmieri** [comment]
![image](https://cloud.githubusercontent.com/assets/22379520/20517063/b00c4a44-b099-11e6-92e1-fdc6254c108c.png)

**Comment by rended** [comment]
'type' è tradotto con 'scrivere' invece di 'tipo' nel secondo passo della controllet

**Comment by rended** [comment]
Italian version completed
