### ISSUE TITLE
Encoding   " (double quote)  in "comments graph" 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#114]
In comment graph:
 1. (double quote): see Prato platform , discussion room (http://prato.routetopa.eu/public-room/#!/31) 
(e.g. "perché è vicino a casa mia" )
2. Href attribute 
![image](https://cloud.githubusercontent.com/assets/22379520/20248073/bd041d3a-a9dc-11e6-841c-9028f770c1c6.png)

**Comment by andrpet** [comment]
Fixed
