### ISSUE TITLE
Controllet: first step organization of resources in dataset (consisting of possibly several resources)

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#117]
In controllet it should index only datasets, understood as a set of resources (eg. xls, csv), and then clicking on a dataset you should open a window that specifies access to the various resources of the dataset. In this way, all the resources of a single dataset are "close", but now if the names are different, even resources of the same dataset can be located far away. This would also make the coherent whole with the CKAN logic.

**Comment by rended** [comment]
Now if a dataset has more than one resource, the new interface instead of a simple list element show a drop down list whit all resources.
