### ISSUE TITLE
Cocreation data: copy and paste between  sheet

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#120]
Copy and  paste from another sheet inside the data room

**Comment by pinapalmieri** [comment]
#132 ,

**Comment by vitsca** [comment]
Wrong closed.. this is still an open and wanted feature

**Comment by luigser** [comment]
It would be usefull know more about this issue. Should be possible copy and paste the entire sheet in to another one ?

**Comment by vitsca** [comment]
The way it was reported to me was to copy and paste a portion of the sheet. The "hope" was to have it from Excel into cocreation room .. but I think it is enough to ensure from a co-creation sheet to another.. or within the same sheet...

**Comment by luigser** [comment]
It seems reasonable but we have to take in account that it can take a lot of time to be implemented so we could think to include this feature after the beta version.

**Comment by luigser** [comment]
We provided this feature in this way:

- Now the user can move in the sheet by using the _arrow_ keys. The selected cell will be highlighted. By pressing the _enter_ key he can edit the cell content and with the _esc_ key can return to selection feature.
- The user can select multiple cells by using at same time the _shift_ and the _arrow_ keys. The selected portion of the sheet will be highlighted.
- After selection the portion of the sheet, the user can use the _arrow_ keys to select the destination cell to copy the content previously copied. If the content copied overflows the destination boundaries the copied content will be truncated to fit the destination space.
- The user can copy/paste some content from excel or from another sheet in a different room. 
- The user can use the arrow keys as well as the muose to select the content to copy and paste.
