### ISSUE TITLE
the list of the cocreated datasets shows the users but not the owner

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#137]
IN the list of the cocreated datasets, it is important to understand who is the owner (if I want to be invited, this is the person that I should contact).. now only a list of users appears.. not clear if the order matters (so the first is always the creator?)

**Comment by andrpet** [comment]
Generally the first user in user list is the owner ... but this is a lucky side effect of the query that read the user. We need to improve this, i think i'll add a new column that explicitly show the room owner.

**Comment by andrpet** [comment]
After a short (but intense :)) brainstorming with @rended, we decided to place a badge on the owner avatar in the user column
