### ISSUE TITLE
Refactor cache machanism and move creation to ODE plugin

### ISSUE THREAD

**Issue by andrpet** [routetopa/spod#138]
Now the cache is limited to hundred of datasets/resources, we have to improve this mechanism.

**Comment by rended** [comment]
In this way Open Wall can be permanently deleted.

**Comment by rended** [comment]
#117

**Comment by rended** [comment]
New cache mechanism is implemented in ODE plugin and support thousands of datasets.
Open Wall is now deprecated and should be uninstalled from all Spod installations.
