### ISSUE TITLE
 Pending message in activity notifications about site activity 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#139]
Pending messages in activity notifcation about site activity, after  marked as read   each message (chat or mail)
(prato.routetopa.eu)
![image](https://cloud.githubusercontent.com/assets/22379520/20426898/7a202fb0-ad81-11e6-8b8e-58825a51100e.png)

or delete history, does not delete the last message
(spod.routetopa.eu)

![image](https://cloud.githubusercontent.com/assets/22379520/20427227/309637e8-ad83-11e6-8df4-83140990471c.png)

**Comment by pinapalmieri** [comment]
Only for Prato platform, enable   "Notifiche Email" button  for already created rooms in the Agora

**Comment by vitsca** [comment]
@pinapalmieri please check if the bug is still there. If not, close the issue, otherwise move it to the milestone 2.5

**Comment by luigser** [comment]
This feature is provided by the "message" oxwall plugin so it is really difficult and 
unseemly to modify if we consider the related problems when we have to upgrade the core basecode
