### ISSUE TITLE
Pagination in controllet does not navigate through search results

### ISSUE THREAD

**Issue by lucavicidomini** [routetopa/spod#143]
How to reproduce:
- Start creating a new datalet
- In step 1 of the controllet, type a keyword in the search box
  - *the list on the left will show relevant datasets*
- Click *Next page* button
  - :exclamation: **the list on the left will go though cached datasets, ignoring the search box**

**Comment by rended** [comment]
fixed
As further improvement the 'searched' text is highlighted.
