### ISSUE TITLE
Integration of multilayer ANCITEL map datalet and map creator in SPOD

### ISSUE THREAD

**Issue by andrpet** [routetopa/spod#144]
ANCITEL created a new map datalet based on openlayer that is capable to visualize KMl, WMS and GeoJSON data on a multi layer map. We need to integrate the authoring system and the datalet inside SPOD.

**Comment by vitsca** [comment]
@andrpet I remember talking also about the inclusion (as a layer) of a "traditional" table-like dataset (with geographical info columns) ... was that realized? if not.. we should discuss it (as it is crucial, especially in the co-created setting, where I want to place some "points" with descriptions over existing layer(s)) ..

**Comment by andrpet** [comment]
We choose to create a new button in My friends' activities/What's new that open the map authoring system ... it seems to work fine and smoothly integrate with the rest of the platform.
Where else we need to integrate this features (comments, my space, agora, everywhere :) ), and how (new button) @vitsca @rended @luigser ?

**Comment by andrpet** [comment]
@vitsca, no ... as it is now map datalet accept only remote dataset (KMl, WMS, GeoJSON)

**Comment by vitsca** [comment]
so, let's involve our developers' team in Ancitel, to discuss with them the issue.. and how complicated it is.. in effect, it is very important to make the "maps" usable..

**Comment by pinapalmieri** [comment]
#59
