### ISSUE TITLE
Cocreation knowledge room: not show suggested dataset created in Library

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#145]
In the cocreation knowledge room, after added a dataset in the Library, the Controllet doesn't  show the suggested dataset (highlighted in yellow?)

(see SPOD User Manual v. 1.8)

![image](https://cloud.githubusercontent.com/assets/22379520/20546091/4e59b19a-b113-11e6-9a2a-58bc33a5d2e0.png)

**Comment by vitsca** [comment]
@pinapalmieri please check if that has been solved (with all the new characteristics) and if that is true, close it. Otherwise, place it in the new milestone 2.5. Thanks

**Comment by andrpet** [comment]
Fixed with @rended
