### ISSUE TITLE
Discussion in Cocreation data: at the end of a post, a link is placed in another thread   

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#147]
1)the link is placed below, in another thread discussion: 
![image](https://cloud.githubusercontent.com/assets/22379520/20680849/239e1fee-b5a1-11e6-9e66-f4ad3f4b3363.png)

2)In any discussion (Whats's new,  Discussion in Cocreation..), a long post that ends with a link  (e.g: www.repubblica.it) and  "see more" appears , the "see more" becomes a link

when the last word is a link (e.g. www.repubblica.it) "see more" becomes a link ()

a long comment that ends with a link, the "see more" becomes that link

![image](https://cloud.githubusercontent.com/assets/22379520/20680608/0ddc484e-b5a0-11e6-8c6f-8be3a03b4c00.png)

**Comment by andrpet** [comment]
We have replaced the discussion tool with another component.
