### ISSUE TITLE
New user registration disabled for Main and Den Haag SPOD

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#149]
Should this be enabled now, as is the case with other pilot SPOD platforms? See [Den Haag](http://denhaag.routetopa.eu/openid/index.php/signin) and [Main](http://spod.routetopa.eu/openid/index.php/signin) SPOD.

**Comment by vitsca** [comment]
The new user registration can be enabled by the administrator.. so the administrator for Den Haag can do it . Of course if they want help, we can do it... @pinapalmieri: can you provide the info about that? thanks

**Comment by pinapalmieri** [comment]
The new user registration is explained in  administrator guide in the section 2.1 
(see the wiki page to download the manual:   https://github.com/routetopa/spod/wiki/Administrator%20Guide%20-v1.10)
