### ISSUE TITLE
Datalet "Export to HTML" fails if exported code is too long

### ISSUE THREAD

**Issue by lucavicidomini** [routetopa/spod#150]
The bug happened on this datalet:
http://spod.databenc.it/newsfeed/1565?ft=site

If you try to Export this datalet (it has a lot of filters) the exported text is cut in the middle and replaced with a "..." that breaks the JSON.

Also, for some reason, Export button is not visible in the permalink such as above (it is however visible if you look for the same post in the newsfeed).

**Comment by rended** [comment]
This is a limit of the function window.prompt() in chrome (2000 chars). We are planning to switch to a custom solution.

**Comment by andrpet** [comment]
I've substituted the window.prompt() function with a custom javascript modal window. The text-area inside the window can accommodate exported datalet of any size.
