### ISSUE TITLE
Cocreation data room:  Default UI  is to split UI with  Dataset and Discussion 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#151]
In the cocreation data room, show UI splitted with Datalet on left side and Discussion on the right side:

![image](https://cloud.githubusercontent.com/assets/22379520/20747103/1d4cde84-b6e9-11e6-9e48-7e8fa7a58346.png)

**Comment by rended** [comment]
Many users prefers the non splitted view as default: databenc users, developers and so on...
To change this default we need the proof that the users preference is changed, it cant be only an opinion of one or few users. We have users experience survey?

**Comment by vitsca** [comment]
The users you are referring to, @rended, are the "power" users, that know how to turn off the split screen. Instead, the "newcomer" users have an initial view of a table.. and nowhere they can ask or collaborate with anybody.. So, I do think that, now that we have more users going to be participating into cocreation, it is better to add the default as "split with discussion on the right"..
