### ISSUE TITLE
Notification of new cocreation room created

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#154]
When any user creates a cocreation room, the moderator(s) are informed via a notification (via mail)

**Comment by pinapalmieri** [comment]
1)Administrator can set an user as  moderator of the Cocreation (data) room 
![image](https://cloud.githubusercontent.com/assets/22379520/21138768/e5e796ea-c12f-11e6-844c-ea18bb3d3eca.png)

2) The moderator of the Cocreation (data) room  receives only those notifications which s/he selected to receive under "My Preferences">>Email notifications  of his/her accounts (see in the attached screenshot, Cocreation section )


![image](https://cloud.githubusercontent.com/assets/22379520/21138961/da4dbb60-c130-11e6-9198-894175b728db.png)
