### ISSUE TITLE
notifications of activities on agora and cocreation

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#155]
By creating a dedicated plugin, one should receive the notifications of each activity. If configured properly, the user receives the aggregate if he/she does not login for 2 days.

**Comment by pinapalmieri** [comment]
In SPOD v. 2.1, Email Notifications in each discussion room of the Agora, and weekly Messages Notifications are available (see screenshot)
![image](https://cloud.githubusercontent.com/assets/22379520/24050062/0dcf9fd4-0b2e-11e7-8381-12c9d93c8ce8.png)
