### ISSUE TITLE
Part  of  Tree Decision in My Space,  is cut off with screen resolution 1280x800 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#157]
Prato team highlights that the Decision Tree tool in My space, testing with a screen resolution 1280 x 800 cuts off part of the GUI.
See screenshots below:

![image](https://cloud.githubusercontent.com/assets/22379520/20945256/d52851c4-bc06-11e6-941f-b7d57e749b18.png)

**Comment by andrpet** [comment]
Fixed
