### ISSUE TITLE
DKAN compatibility lost?

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#16]
We had the compatibility with DKAN. When you tried at confiscatibene.it to use one of their datasets, they are shown as a single JSON item in the second step of the Controllet. The link where you can try is http://www.confiscatibene.it/it/node/101/api and the example query is: http://www.confiscatibene.it/it/api/action/datastore/search.json?resource_id=60e7746b-89a2-4bda-8c8a-82918437d23b

**Comment by rended** [comment]
Now we are compatible.

The header fields should not contain the comma character ','  like in

http://www.confiscatibene.it/it/api/action/datastore/search.json?resource_id=60e7746b-89a2-4bda-8c8a-82918437d23b

or the controllet does not work (regardless of the provider).
