### ISSUE TITLE
Cocreation knowledge: authoring color same color for each user

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#160]
(Den Haag Pilot session on 23-11-2016)

Authorship color
•	Authorship color changes when users log in from different computer, this confuses the co-creation process. Should be the same color for one user, independent of the computer user logs in. 
•	Authorship colors are not the same for all phases, same confusion as above.

**Comment by vitsca** [comment]
Working on Etherpad is very time consuming and then it is very costly but not extremely important to justify the effort
