### ISSUE TITLE
Authorship color disappears regularly

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#161]
(Den Haag Pilot session on 23-11-2016)
Authorship color disappears regularly when users are working in the co-creation room; sometimes the box in the menu is unchecked spontaneously, but also cases where there is no color when the box is still checked.

**Comment by pinapalmieri** [comment]
(Sent from Den Haag  by e-mail, November 30 2016 )
Most of the participants were working on a mac - I think the latest IOS, one on a windows (?) and one on a tablet (apple). The tablet was not really working well, after everything he typed he was directed to the top of the page and had to scroll back again to where he was typing.

**Comment by vitsca** [comment]
This is the expected behaviour, as the coloring is not the default and must be activated each time the page is reloaded. The coloring is not on by default because we have found several reports of users that find it annoying
