### ISSUE TITLE
Cocreation knowledge: problems of  synchronization

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#162]
(Den Haag Pilot session on 23-11-2016)

Working synchronous in the knowledge room:
•	When six users work synchronous, the co-creation room stops working regularly (increasingly during the one hour session, at the end every minute and a lot of errors when reloading). Stop means users cannot type anymore. After reloading it most of the time works again, but then it stops again after few minutes. 

•	Six users at the same time is not a lot, but too much for the co-creation knowledge room. How about in the co-creation data room? It is designed for synchronous working on making datasets; so that should be possible. Same should be possible for co-creation knowledge room. 

•	Complementary bug: when five users type at the same time, their cursor disappears, or appears at different line of text or they sometimes type over text of other users

**Comment by andrpet** [comment]
We have completely changed the cocreation architecture and improved scalability since 7 Dec 2016
