### ISSUE TITLE
My space: problem 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#166]
Private space  doesn't allow to work on it (issue on Issy, Spod, DenHaag, Goningen, ddac, platforms)

![image](https://cloud.githubusercontent.com/assets/22379520/21180162/fe02a2ec-c1f7-11e6-9d51-4275853910e4.png)

**Comment by rended** [comment]
Fixed, the bug was due to the cancellation of old datalets no longer in use but imported into my space.
