### ISSUE TITLE
Controllet:  not working the "show last" version of the "FROM COCREATED " tab

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#168]
In the Controllet, in "FROM Cocreated " tab, click on "Show all" show all versions of a dataset 

![image](https://cloud.githubusercontent.com/assets/22379520/21184015/d5ad56e4-c20a-11e6-90cc-ce534edf7727.png)

When in "FROM Cocreated " tab, click on "Show latest" show all versions of a dataset
![image](https://cloud.githubusercontent.com/assets/22379520/21184151/6ec00cfa-c20b-11e6-9abd-ddec6abdf7ac.png)

**Comment by rended** [comment]
Fixed
