### ISSUE TITLE
More information on the profile of a user (?) 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#172]
(Den Haag Pilot session on 23-11-2016)

Another suggestion is to add to the profile questions some questions about roles users like to have in these processes, such as chairman (or women), mediator, moderator etc.. Furthermore users wanted to be pointed to these roles more (for instance add a phase 0 – regulation of the co-creation room), so that these roles or talk about the process can be taken into account in the co-creation room.

**Comment by andrpet** [comment]
Privacy is a very delicate topic for our users. It turned out to be very difficult to ask for personal information to users.
