### ISSUE TITLE
In Agora, activities related creation a new co creation room doesn't show text, only avatar

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#173]
In Agora, the activity about "create a new cocreation room",   clicking   on the bell icon located in the top right corner, shows only avatar and not text of the notify 

![image](https://cloud.githubusercontent.com/assets/22379520/21268013/25fb97ca-c3ad-11e6-9fa5-68b12b65eb42.png)

**Comment by andrpet** [comment]
This issue not apply longer to the current version of Agora
