### ISSUE TITLE
Maplet : User Interface  not clear: overlap of strings

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#174]
(feedback from Prato in December 20-12-2016)
 In the ODN  open data portal  (http://odn.comune.prato.it/) of Prato,  KML files  are available (an example: http://odn.comune.prato.it/dataset/archi_strade/resource/092c3ea0-563b-47e0-a5b4-288b2103ac01).

In SPOD plaform, when address of KML files (such as : 	http://odn.comune.prato.it/it/storage/f/2016-06-23T105735/archi_strade.kml) is used in the maplet (Ancitel feature), in  the STYLE section  tab, the style of layer   shows overlap of text with other ui components

![image](https://cloud.githubusercontent.com/assets/22379520/21346783/2b1cfb58-c6a6-11e6-8cdd-d3ddd03ebaac.png)

**Comment by andrpet** [comment]
UI of map controllet is drastically changed
