### ISSUE TITLE
Maplet:  Multilayer  doesn’t seem to work with dataset of Opendatasoft portal

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#180]
(Feedback about SPOD v. 1.10 on December 16, 2016)

Ancitel Multilayer doesn’t seem to work. While indicated title and type of file, it is pasted in the url field the related url (tried Geojson, KML and API) with not success. 

Dataset tested is:
https://data.issy.com/explore/dataset/parkings-partages-bepark-a-issy-les-moulineaux/api/?disjunctive.commune

**Comment by andrpet** [comment]
Fixed
