### ISSUE TITLE
Datalet with “Geojson Map” doesn't show  correctly  the map

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#182]
(Feedback about SPOD v. 1.10 on December 16, 2016)

While creating a datalet with “Geojson Map” the map is correctly created, but the map is not zoomed on right place (it zooms on Indian Ocean) 

![image](https://cloud.githubusercontent.com/assets/22379520/21616229/fbb50464-d1e0-11e6-808f-aab923666d1c.png)

**Comment by rended** [comment]
fixed
