### ISSUE TITLE
Maplet: feature "Modify" makes empty UI of the "Select style of layer"

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#185]
(Feedback on SPOD version 1.11, December 20, 2016)

Test with "Service url = http://odn.comune.prato.it/it/storage/f/2016-10-20T100508/biblioteche.kml"
1) Modify a layer
![image](https://cloud.githubusercontent.com/assets/22379520/21618352/cca2e024-d1ea-11e6-9e43-87175a1db4d5.png)

2) Style UI is empty
![image](https://cloud.githubusercontent.com/assets/22379520/21618373/eb913030-d1ea-11e6-9491-0106ea533f8c.png)

**Comment by andrpet** [comment]
Refer to the old version of the maplet
