### ISSUE TITLE
Maplet:  magnifying glass (search) icon doesn't work

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#186]
(Feedback on SPOD version 1.11, December 20, 2016)

No functionality when clicking on the magnifying glass (search) icon

![image](https://cloud.githubusercontent.com/assets/22379520/21618616/1403f894-d1ec-11e6-9a29-d41cec862692.png)

**Comment by andrpet** [comment]
Refer to the old version of the maplet
