### ISSUE TITLE
Agora: the title (Commentaire du graphique) gets out of the framework in room

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#19]
For Graphs, the title gets out of the framework. See image 2 on annex. 

![image](https://cloud.githubusercontent.com/assets/22379520/19081426/85c25b80-8a5a-11e6-9df4-d777f3ace26b.png)

**Comment by rended** [comment]
Bug fixed

![immagine](https://cloud.githubusercontent.com/assets/17746902/19120886/d096c158-8b24-11e6-8794-fe1437477fd6.png)
