### ISSUE TITLE
Visualization problem of a map  with cocreated dataset (16 records)

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#193]
Feedback from Prato (sent via e-mail) 

Visualization problem of a map with a cocreated dataset with 16 records

![image](https://cloud.githubusercontent.com/assets/22379520/21991238/0eadcb38-dc12-11e6-9f90-e4875f5be484.png)

**Comment by pinapalmieri** [comment]
Viusalization problem  of the legend in the histogram of a dataset with 178 records:
![image](https://cloud.githubusercontent.com/assets/22379520/22158674/946efcc8-df3d-11e6-807f-2e0eb438636e.png)

**Comment by rended** [comment]
Fixed: now with highstock (for charts) and markercluster (for maps) we can handle and display large datasets!
