### ISSUE TITLE
Controllet: error in check of data types

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#194]
In  step 2) of  Controllet  the library to control the data types  gives error when is 3,04  (see screnshot)

![image](https://cloud.githubusercontent.com/assets/22379520/22886380/d762fc5a-f1fd-11e6-9ec4-b438bb3ae282.png)

**Comment by donpir** [comment]
Solved the issue, by improving  the regular expression (/^(0|([0-9]+))$/g
