### ISSUE TITLE
French Translations on Issy platform

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#200]
Feedback sent by e-mail sent in February 14th 2017

1. [pptx presentation](http://service.routetopa.eu:8000/f/b99cc2eaaa/) with all strings to translate in French 
2. Helper on line to organize
3. Waiting the final User Guide to store on line

**Comment by pinapalmieri** [comment]
Cocreation data room: new strings to translate  
	Name your spreadsheet:	
	"Go to the sheet",	
	"Manage Sheets",	
	"View Functions",	
	"Style Sheets and Cells",	
	"View Activities and Timeline",	
	"Format Cell",	
	"Sort Row",	
	"Remove Row",	
	"Add Row",	
	"Single row",	
	"10 rows",	
	"Remove Column",	
	"Add Column",	
	"New Sheet",	
	"Export CSV",

**Comment by pinapalmieri** [comment]
Check HTML formatting in the Data policy page:
    
http://issy.routetopa.eu/Data-policy

**Comment by pinapalmieri** [comment]
List of strings in the Donato' Librar:


![image](https://cloud.githubusercontent.com/assets/22379520/23865386/d78955de-0815-11e7-8937-4f1aeb4d983b.png)

**Comment by pinapalmieri** [comment]
(Issy feedback (via- email) in April 4 2017)

French Strings for Controllet in the step 2) ( @donpir) 

 
![image](https://cloud.githubusercontent.com/assets/22379520/24654060/8b2a777a-1938-11e7-9321-5fad43f2d181.png)

**Comment by donpir** [comment]
I updated the library JSDataChecker with the translations. Renato @rended will deply it on SPOD.

**Comment by pinapalmieri** [comment]
Fixed helper on line!
