### ISSUE TITLE
AGORA in SPOD 2.1: the vertical space on the "discussion" part can be improved

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#212]
It looks like there is some empty space in the chat of the agora, indicated by the arrow.. In general, is there some way to further allow more space for the chat (in vertical)? For example, finding some space or other way to render the title/subtitle? Or to render the participants? @rended 

![schermata 2017-03-21 alle 19 16 43](https://cloud.githubusercontent.com/assets/2544302/24163685/96cc15e8-0e6b-11e7-9c82-e441940d3eeb.png)

**Comment by rended** [comment]
#243
