### ISSUE TITLE
Controllet: add tooltip for fields with long names

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#213]
In step 2 the names of the fields may be long and are actually cut after few characters. 
It makes difficult to select them from the list to the left, and also recognize them in the heading of the table of the selected columns. A tooltip can easily show the full name ..

**Comment by vitsca** [comment]
I think this is really needed.. in many cases, the names are very long and non informative.. I would say it is no longer minor..

**Comment by rended** [comment]
Tooltips added
