### ISSUE TITLE
Agora 2.1: Enable Privacy  message 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#219]
In Agora, enable privacy message when you're offline (see screenshot)

![image](https://cloud.githubusercontent.com/assets/22379520/24286566/0e31fcfe-1076-11e7-95cb-c3af9500349b.png)

**Comment by vitsca** [comment]
@rended please check the status. If it is working, now, then close the issue. Otherwise, move it to next milestone 2.5

**Comment by andrpet** [comment]
Fixed
