### ISSUE TITLE
To choose (as admin)  color and order of the room 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#22]
(SPOD v1.7+1.8, September, 20 2016)
Impossible to choose the order and the colour of the rooms (as administrator). Actually, the order and colour of rooms is important to be set by admin/moderators to make possible for users to quickly understand where they are.

**Comment by luigser** [comment]
The order, size and color of the rooms have a specific meaning as reported in the related release notes and in the manual in the relative section.

**Comment by pinapalmieri** [comment]
In SPOD v. 2.01,  Agora and each public room have been totally redesigned with new User Interface
