### ISSUE TITLE
Agora 2.1: add a functionality “go back” 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#222]
Issy feedback, March 22 2017

On Agora rooms, we do not have a functionality “go back” that would be useful

**Comment by rended** [comment]
To go back you can click on the tab Agora or (in new Agora) use the go back browser button.

**Comment by pinapalmieri** [comment]
(Utrecht University Feedback , 21th April 2017)
When you click on one of the rooms, there is no possibility to go back to where you can choose all the rooms. There should be some button ‘back’ where you can go back to selecting a room. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/22379520/26633813/f69d418c-4614-11e7-95a5-b945b9d9e638.png)

**Comment by andrpet** [comment]
Added a big back arrow to go back to agora list
