### ISSUE TITLE
Agora: UI problems

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#223]
(Prato Feedback in March 23 2017)

See details and  screenshots for UI problems:
problem with "Entra" button in Prato platform

Setting Chrome:
- zoom = 110%

Resolution setting:
- 1440x900 resolution

(1) ![image](https://cloud.githubusercontent.com/assets/22379520/24291230/5fdea9b4-1088-11e7-820d-81cf565feb92.png)

(2) 
![image](https://cloud.githubusercontent.com/assets/22379520/24291259/7789087a-1088-11e7-8e36-a1eed10fcc85.png)

**Comment by rended** [comment]
#224
