### ISSUE TITLE
Agora 2.1: comments on the new UI 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#224]
(Prato feedback in March 23 2017)
Comments on new UI of teh Agora v2.1:

(1) Tabs  do not clear 
(2) The column on the right side  is much empty and shows big elements
(3) The rectangles of each public room are too  big
(4) Delete Latin proverb (A communi observantia non est recedendum.) 
(5) Abbreviations
![image](https://cloud.githubusercontent.com/assets/22379520/24292029/cba0fba4-108b-11e7-8e01-73694aa95f5e.png)

**Comment by rended** [comment]
1) Text inside tabs is customizable by platform administrator. (1st tab sort Agora by creation time, 2nd tab  sort by number of unread comments, 3rd tab sort by number of comments, 4th tab show only Agora created by logged user)
2) Layout improved, empty spaces are significantly reduced (tested from 1000x800)
3) The size of rectangles has been reduced
4) Deleted
