### ISSUE TITLE
Time of the day is wrong on spod.databenc.it

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#228]
Time of the day for the comments in the Agora are not correct .. these comments were done around 4pm of today.. 
![schermata 2017-03-27 alle 16 14 39](https://cloud.githubusercontent.com/assets/2544302/24360902/dd9039ae-1308-11e7-99e2-5d28bdf3a515.png)

**Comment by lucavicidomini** [comment]
Time is fine on console, system settings and what's new. Probably a plugin-related bug. Bounce to @andrpet @rended @luigser

**Comment by vitsca** [comment]
a clear example of "passing the bucket" .. right? :-) it is not me.. it is the software 👍  :-) @andrpet @rended @luigser @lucavicidomini

**Comment by andrpet** [comment]
Fixed (under testing) with a different ntp server
