### ISSUE TITLE
[Bug]New user registration form error

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#229]
New user has trouble registering after signing up in groningen.routetopa.eu
They receive the following message despite filling in the form completely: 
The VUL HET FORMULIER VOLLEDIG IN AUB
[See screenshot](https://drive.google.com/file/d/0B_JaJ8nU_3FGNFlJbm9jcnlqTnM/view?usp=sharing)

**Comment by pinapalmieri** [comment]
Fixed Bug, try again your registration.
 A required field in the "Edit profile question" has been  modified.
