### ISSUE TITLE
Controllet: problems with map 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#230]
(Feedback from Issy, in March 31 2017)
See the following screenshots:
The dataset is " Localisation des bureaux de vote à Issy-les-Moulineaux"  
(1)
![image](https://cloud.githubusercontent.com/assets/22379520/24547502/7412a27c-1610-11e7-8b06-e964421bd45d.png)
(2) 
![image](https://cloud.githubusercontent.com/assets/22379520/24547541/a6dbbbee-1610-11e7-97ed-76acf8509fee.png)

**Comment by andrpet** [comment]
fixed
