### ISSUE TITLE
Controllet: Opening the page of the dataset doesn't work 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#237]
![image](https://cloud.githubusercontent.com/assets/22379520/24794101/a5f00446-1b84-11e7-985f-4047bcf87812.png)

Try to open the following page
http://dati.mit.gov.it/dataset/c195235f-8ebf-487e-8e22-b35dc49d666b/resource/1b8dbf76-2798-420e-a8a3-e04d28ac3947

instead the correct address is 
http://dati.mit.gov.it/catalog/dataset/c195235f-8ebf-487e-8e22-b35dc49d666b/resource/1b8dbf76-2798-420e-a8a3-e04d28ac3947

**Comment by andrpet** [comment]
duplicated issue #288
