### ISSUE TITLE
New user registration disabled

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#238]
On [spod.routetopa.eu](spod.routetopa.eu), new user registration is still disabled. [See screenshot with error message](https://drive.google.com/file/d/0B_JaJ8nU_3FGTHc1eVdqZVJ2ODA/view?usp=sharing)

**Comment by pinapalmieri** [comment]
New user registration is disabled on spod.routetopa.eu as the platform is just for demo and is not "managed" by any community manager.

**Comment by callmealien** [comment]
ok, thanks for the response @pinapalmieri. Was hoping to use it in a presentation this week. I'll show one of the pilot ones.
