### ISSUE TITLE
Layout of the new agorà room is taking too space in vertical

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#243]
The title, subtitle and the list of participants is taking to much room.. see example
<img width="839" alt="schermata 2017-04-21 alle 14 30 37" src="https://cloud.githubusercontent.com/assets/2544302/25293218/7ab1933c-269f-11e7-87f8-90dfc262a612.png">

**Comment by rended** [comment]
Fixed, now the space is used much better.
