### ISSUE TITLE
Agora client side stress test

### ISSUE THREAD

**Issue by andrpet** [routetopa/spod#245]
The idea is to modify the notification system (nodeJs) in order to send a large amount of (fake) messages to check the performance and the stability of the agora.

**Comment by andrpet** [comment]
Any suggestion ? Number of messages, rate (comments/seconds) ? Number of datalets ? @vitsca @rended

**Comment by vitsca** [comment]
"Make it configurable" :-) ... jokes aside, I think that we can get some data from @donpir about the workload of a social network.. the number of datalets is of course only ours, so I think we can only get some data from some discussions (the ICT Master for Cultural Heritage) and get a rate similar to it (no.datalets/no.ofcomments)

**Comment by vitsca** [comment]
Delfina is the master here.. cannot tag her, but she is the one to ask.. only found this paper (old) http://dl.acm.org/citation.cfm?id=1644900 that provides some data om the workload associated..

**Comment by andrpet** [comment]
We choose to create a test program with these parameters:

- actions/s (where action can be comment or comment + datalet)
- rate datalets/comments
- message length
