### ISSUE TITLE
Agora: Not clear how  the "Sentiment" feature works

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#251]
Issy Feedback May 02 2017 (via e-mail)

Any user clicks on the "sentiment" icon and  "Italian message" (Messaggio vuoto) appears
![image](https://cloud.githubusercontent.com/assets/22379520/25672574/6dfad484-3034-11e7-80cd-d11b235a37c4.png)

**Comment by rended** [comment]
Fixed
