### ISSUE TITLE
Adding a comment on spod.databenc.it doesn't work...at first

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#253]
When adding a comment on the Newsfeed of spod.databenc is not working: it appears a message on the top "ERROR" and then it keeps reloading. When you reload the page, the comment is there.. 
Comment as shown in the image. Browser Opera on Mac .. 
![schermata 2017-05-03 alle 19 20 54](https://cloud.githubusercontent.com/assets/2544302/25672932/e8ce1c56-3035-11e7-87a6-cd3b57d52bf0.png)

**Comment by rended** [comment]
fixed
