### ISSUE TITLE
On nl-spod the sequence of tabs is mixed up..

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#261]
It should be "what's new, member, private, agora, cocreation" 
![image](https://cloud.githubusercontent.com/assets/2544302/26491243/0e34e778-420f-11e7-83ab-0623428c31ec.png)

**Comment by andrpet** [comment]
https://softwareengineering.stackexchange.com/questions/225400/pros-and-cons-of-facebooks-react-vs-web-components-polymer

2017-05-26 12:30 GMT+02:00 Vittorio Scarano <notifications@github.com>:
