### ISSUE TITLE
Blog: SPAM word in upper case

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#264]
(Utrecht University  feedback in 21th April 2017 )

In the (for me ) new feature Blog, you can do several things. If I am correct the meaning is something like Instagram Stories but then with Open Data. In general, the feature is very cool and can instigate a lot of discussion on the platform. However, you can either ‘rate’ the blog with a number of stars (on the right side), or ‘Flag’ the blog. This is a prominent button where you can say SPAM, offence, or illegal. I would make this button smaller and put it somewhere else less prominent. This way you encourage people to think of blogs as offensive or spam. 
Also the word SPAM should be with normal letters. See below screenshot,  for more info. Furthermore, it would be a good feature if you could react on blogs, so there is the possibility for discussion about the blog. 

![image](https://cloud.githubusercontent.com/assets/22379520/26633921/47a36d68-4615-11e7-8d1f-3c5eb2efde3b.png)

**Comment by vitsca** [comment]
This is several request at once. 
- SPAM: does it mean to intervene in the original core of the platform Oxwall? If that is the case, it is not something easy to mantain and sustain.. so I would say it cannot be done. If it is in our plugin: just do it. The same for position of buttons, etc. 
- Discussion under the blogs: it is still another place where discussions could take place (besides in Agora rooms, in newsfeed, in cocreation rooms).. I think it should not be done. Consider this request closed

Please, @pinapalmieri .. react to these comments.. If the SPAM cannot be done, close the issue

**Comment by pinapalmieri** [comment]
Change in admin panel,  modify  "SPAM" string in the "base" plugin in each SPOD platform (Blog plugin is activated in Prato and SPOD platfroms).
