### ISSUE TITLE
Cocreation: not clear how go back to the list of all cocreation rooms

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#265]
(Utrecht University  feedback in 21th April 2017 )

When you go to the list of co-creation rooms you can not enter any of them. You can only click on open (and then you are stuck), download, docs, or copy link. All of them do not give me the screen as shown in the update of Tabita. See screenshot  below

![image](https://cloud.githubusercontent.com/assets/22379520/26634171/0deb2cea-4616-11e7-89aa-e80654daae42.png)

**Comment by vitsca** [comment]
@pinapalmieri ... I don't understand the comment.. can we (ask them to) clarify?

**Comment by pinapalmieri** [comment]
Maybe they did not understand what it was for. I suggest move it to next release adding  a tooltip with more details

**Comment by rended** [comment]
Utrecht misunderstand the purpose of the list: this isn't the cocreation rooms list but the cocreated datasets list as the label on the top of the table suggest.
