### ISSUE TITLE
Agora: two small things

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#266]
(Utrecht University  feedback in 21th April 2017 )

The new agora looks very professional and clean. It is a big improvement compared to the previous version. Two small things could be better:
(1) I expected to go to the room directly when I double click on the room on the left. Now I had to search for the button to go there. It feels a bit unnatural. Maybe it could be a combination of both.

(2)Furthermore, I would like to see some of the comments on this screen already so I can decide wether it is interesting to go there or if there are new comments since the last time I visited. See screenshot below. 

![image](https://cloud.githubusercontent.com/assets/22379520/26635019/aef1dc90-4618-11e7-8a49-dc1cf36c8b76.png)

**Comment by pinapalmieri** [comment]
(1) Double click to open a room in Agora: Fixed

**Comment by vitsca** [comment]
request (2) is too heavy because of the limited screen size...
