### ISSUE TITLE
Agora: messages notification

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#267]
(Utrecht University  feedback in 21th April 2017 )

When you are in the Agora room, you see still displayed ‘19’ messages, while you have already read them. Like on Facebook, this sign should disappear when you have read the messages. See screenshot below

![image](https://cloud.githubusercontent.com/assets/22379520/26635435/084a82be-461a-11e7-802e-b600ec0dfbfb.png)

**Comment by andrpet** [comment]
The message number represent the number of unreaded messages from the last time that user left the room. Once the user reconnect to the room we assume that all the unreaded messages are visualized (as facebook or whatsapp). So reloading the page the number drop to zero
