### ISSUE TITLE
Cocreation: not clear where to look for other co-creation rooms

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#268]
(Utrecht University  feedback in 21th April 2017 )

In Co-Creation when you click on it it only shows your co-creation rooms. Then it is not natural to look for the list button to see all the others. This should be made more clear, where you can find the other co-creation rooms. Maybe with a word or a clearer symbol. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/22379520/26635558/76a72eba-461a-11e7-96a7-eba411f94716.png)

**Comment by andrpet** [comment]
It's an incorrect interpretation of the page. Here are listed all the cocreation rooms created by the user and the room where is invited. No other cocreation room are available for user (so you cannot find anything). The mentioned list is of all the cocreated datasets.
