### ISSUE TITLE
Cocreation: import wizard  for  CSV data  

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#269]
Introduce a Import Wizard with formatting options.

(See attached document (IT version) https://github.com/SPOD-Lab/Deployment/blob/master/Documents/LineeGuidaImportazioneCSVDati_ROUTETOPA_20170531_v1.0_it.pdf)

**Comment by donpir** [comment]
I improved the import dialog layout and checked the following two things:

* CSV file must have a header (not an empty line);
* all the rows must have the same number of fields.

More checks must be implemented.

**Comment by donpir** [comment]
Improved the importing of a CSV file. Now, the importing recognizes that:

 * the header (first row of the csv) has fields without a caption;
 * the csv file contains empty rows (otherwise ethersheet throws an Exception).
