### ISSUE TITLE
Incomplete profile prevents users to access static pages

### ISSUE THREAD

**Issue by lucavicidomini** [routetopa/spod#272]
When a new user registers, Oxwall asks him/her to complete the profile . While the profile is not complete, user can't access any page. This prevents users to read the Privacy policy and Data policy while on this state.

**Comment by lucavicidomini** [comment]
This is how NL-SPOD was patched, while waiting a definitive solution.

File: `ow_system_plugins/base/classes/event_handler.php`
At line 398, replace:
```
    public function onPluginsInitCheckUserStatus()
    {
```
with:
```
    public function onPluginsInitCheckUserStatus()
    {
        $attrs=OW::getRouter()->getUsedRoute()->getDispatchAttrs();
        $controller = $attrs['controller'];
        if ($controller == 'BASE_CTRL_StaticDocument')
            return;
```

**Comment by vitsca** [comment]
resolved (many releases ago :-))
