### ISSUE TITLE
Bug; the datalet with "many" data, does not begin from the left but from the right

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#274]
The datalet (example in hetor.databenc.it/site/adiaz/weblet/ under "Casellario Politico" begin from the rightmost position zoomed in and not from the leftmost ones, as we decided, @rended. 
It was supposedly been changed but now it shows again the items on the left..

**Comment by vitsca** [comment]
Please fix it first time on tuesday morning, @rended, as I have the demo at the school ...

**Comment by vitsca** [comment]
Please @rended could you fix it? thanks

**Comment by rended** [comment]
It's working, but it depends on the version of the deep that you use. This change has been activated from version 1.15 onwards. For Datalets out of SPOD is advisable to use the non-versioned deep which is constantly updated.
