### ISSUE TITLE
DIscussion in the cocreation automatically adds a datalet :-)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#275]
When in the cocreation , a user builds a datalet, and THEN, writes something on the discussio, the same datalet is added to the discussion .. :-) probably this is not wanted, although, some times, it may be a feature.. :-)
Nevertheless, I think it is a bug .. it should be corrected, agree @andrpet @luigser and @rended ?

**Comment by vitsca** [comment]
@rended please, could you fix it? thanks

**Comment by andrpet** [comment]
Platform ? @vitsca

**Comment by vitsca** [comment]
What a question! Macosx, chrome.. the room is on spod.databenc.it.. you can ask Gianluca to invite you .. I am not the owner... in this case, I first created the datalet in the cocreation room.. and then, went on and submitted a comment WITHOUT adding it.. and was added automatically
![schermata 2017-06-15 alle 17 20 14](https://user-images.githubusercontent.com/2544302/27188702-5431e1aa-51ef-11e7-9f8e-2361206dd074.png)

**Comment by luigser** [comment]
It's a bug. We are working to fix it.

**Comment by andrpet** [comment]
fixed
