### ISSUE TITLE
Cocreation data: making some fields as optional  when a new data room is created

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#276]
Making optional fields when a new data room is created (see screenshot)

![image](https://user-images.githubusercontent.com/22379520/27233290-4003f658-52b9-11e7-94e5-4297bfdd2b47.png)

**Comment by andrpet** [comment]
We need to discuss about which fields are mandatory and which optional. Some fields are strictly necessary according our database structure and code implementation

**Comment by vitsca** [comment]
Yes... I would say that (if possible, given the structure of the database and code) mandatory should be: 
Name, Subject, Description (?).. 
and optional all the others.. is it possible?

**Comment by vitsca** [comment]
Make mandatory: name, subject and description, date
Date: default beginning: time of the creation, end: if possible "null date" otherwise: 1 week)
Optional: all the rest

**Comment by andrpet** [comment]
Fixed as described by @vitsca
