### ISSUE TITLE
Turning on the notification mail by default (for participants)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#279]
Turning on the notification mail by default (for participants): if you contribute to a room, or create it .. turn the notification email on right away (then later the person can turn it off).. 
only the first time it contributes. (add a comment, like or else)

**Comment by andrpet** [comment]
The automatic subscription for mail notification is now implemented for the room creator. For room users, now, when notification is enabled in the room page the parent action is enabled also in the notification panel.
