### ISSUE TITLE
SPOD E-mail notification plugin: message to translate

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#283]
From menù : SPOD Email Notification

Clicking on the "SAVE Settings" button,  following string to translate appears

![image](https://user-images.githubusercontent.com/22379520/27783131-3f479a98-5fd5-11e7-88f6-0a1ea8b2b2e8.png)

**Comment by pinapalmieri** [comment]
(Internal testing in June 22,  2017)
When an user receives e-mail,  the message contains a word (e.g. {$roomname}) to delete 
see below screenshot:
![image](https://user-images.githubusercontent.com/22379520/27785751-dfe4da5c-5fde-11e7-890a-1601bfbd50cc.png)

**Comment by andrpet** [comment]
Fixed with a new panel for notification user settings
