### ISSUE TITLE
Cocreation data room:  adding 10 rows 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#284]
(see Internal Testing in 22 June 2017  )
The following features 
-   ADD Row -> 10 rows

doesn't work.

**Comment by vitsca** [comment]
@pinapalmieri and @luigser : if it works, close it.. if it doesn't, we keep it open and add it to the milestone 2.5 ...

**Comment by andrpet** [comment]
Fixed by @luigser
