### ISSUE TITLE
Agora: users graph doesn' t show avatar

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#285]
Issy platform,  in a discussion room, the usr graph doesn' t show avatar between users (e.g., in Administration room)
(see below screenshot)
![image](https://user-images.githubusercontent.com/22379520/27850463-28c55248-6155-11e7-9d44-b618913b4453.png)

**Comment by rended** [comment]
![userg](https://user-images.githubusercontent.com/17746902/27952026-2ae2f5cc-6307-11e7-8ff2-de40d764a58f.png)

Fixed
