### ISSUE TITLE
SPOD Tour:  in the first page, adding  "enlarge" feature for the datalet

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#286]
Feedback from Prato , July 10th 2017
Sharing a datalet on Facebook, the datalet of the SPOD Tour (first page) doesn't show "enlarge" button on the right side. 

See screenshot below:

![image](https://user-images.githubusercontent.com/22379520/28015569-d0540cec-6570-11e7-8e12-9bcb209f82c3.png)

**Comment by andrpet** [comment]
The enlarge button is voluntary hidden in the datalet landing page
