### ISSUE TITLE
Map doesn't allow to add more balloons selecting only three fields 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#287]
Feedback from Prato (July 11th 2017)

Controllet, when in the step 2) three fields selected ( the coordinate field is a pair of values, ),
(see below screenshot)
![image](https://user-images.githubusercontent.com/22379520/28076494-32854540-665f-11e7-8e53-35c99d2fccc6.png)

The step 3 doesn't allow to add two ballons (see Screenshot below)

![image](https://user-images.githubusercontent.com/22379520/28076524-4d43471a-665f-11e7-8b3d-bd7cc1d17b1c.png)

**Comment by rended** [comment]
Fixed
