### ISSUE TITLE
Link from a datalet to a dataset not working for Regione Lazio

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#288]
When I create a datalet from this dataset: http://dati.lazio.it/catalog/it/dataset/pronto-soccorso-accessi-in-tempo-reale/resource/4a5a084c-b63c-4f4d-b3f0-b1163c0ad077
the datalet is correctly created, but the link to "dataset" shown, bring to this page that does not exist: 
https://dati.lazio.it/dataset/undefined/resource/4a5a084c-b63c-4f4d-b3f0-b1163c0ad077
while the correct page for the dataset is:
http://dati.lazio.it/catalog/it/dataset/pronto-soccorso-accessi-in-tempo-reale/resource/4a5a084c-b63c-4f4d-b3f0-b1163c0ad077

**Comment by rended** [comment]
f fixed
