### ISSUE TITLE
Cocreation add datalet does not work

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#290]
Regione Campania spod: in a cocreation room, when adding a datalet http://opendata-crc.di.unisa.it/spod/cocreation/data-room/27 it shows a url of the site of the Regione Campania instead of the controller.. moreover it shows in the number of datalets (bottom left) the "!" instead of 0... 
![image](https://user-images.githubusercontent.com/2544302/28473971-0b5c3ff6-6e47-11e7-8535-65dd8e876c10.png)

**Comment by vitsca** [comment]
on databenc spod it works.. although it still shows a "!" instead of a 0/0

**Comment by rended** [comment]
Fixed
