### ISSUE TITLE
Cocreated dataset is not accesible (regione campania site)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#291]
The dataset "Interrogazioni Esempio" cocreated (Regione Campania site) under room 27 is not accessible: infact the link that is shown in the list of cocreated datasets: 
http://opendata-crc.di.unisa.it/cocreation/ajax/get-dataset-by-room-id-and-version/?room_id=27&version=1
does not bring anywhere... page not found

**Comment by andrpet** [comment]
fixed
