### ISSUE TITLE
Error in the timeline date (US FORMAT INSTEAD OF ITALIAN ONE!)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#293]
Very weird: the dataset in http://spod.databenc.it/cocreation/data-room/244 is shown in the timeline datalet (shown in the cocreation room) only partially.. 
Ohhh.. just discovered what! .. The data of the timeline are only in the US style MM/DD/YY... so, the july 3rd 2017 03/07/17 is shown as March 7th 2017 .. and the ones above 12 (for the months position) are not shown! URGENT

**Comment by andrpet** [comment]
Now there is a data type drop-down-list that allow the data type selection by user
