### ISSUE TITLE
Timeline and media slider datalets: add more descriptive fields and allow also URL, if recognized as such

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#294]
It should be possible to add more fields (of the table) in the description.. not just one as it is now. 
Say at least, 3-4 fields... (I don't think we can infer how many..) besides the traditional media and background.. 
Moreover, if one of the fields added is a URL, it would be great if it is added with a link to open (in another frame of the browser) the url.. Maybe, we may add a field "URL" where one can add a field that contains urls that are hyperlinked..

**Comment by rended** [comment]
#360

**Comment by rended** [comment]
Now is possible select multiple description fields
