### ISSUE TITLE
Publishing on Facebook: missing title and description from the landing page

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#295]
It seems that the landing page has no title/description metadata, incurring in poor showing on Facebook .. "No Title" "No Description"
<img width="512" alt="schermata 2017-07-22 alle 10 58 26" src="https://user-images.githubusercontent.com/2544302/28489846-049455ce-6ecd-11e7-897a-81fa09cfebc5.png">

**Comment by rended** [comment]
That beacause the Datalet has no title and no description... we should think of a default in these cases.
Eg.
"Bar Chart Datalet"
"A visualization from the dataset NomeDataset"

**Comment by vitsca** [comment]
Yes.. I tried and it worked (about the title).. still having problem on hetor spod on the "caching" from Facebook side.. now it does not show the preview.. what is a good practice about it? wait 2 minutes before publish it? or what? @andrpet

**Comment by andrpet** [comment]
I quote @rended  for datalet title and description (we need some defaults). About sharing from hetor i've tried with the last datalets created on the platform (newsfeed) and everything works fine. The image creation take about 10s. I don't know (and it is not specified in facebook documentation) if there is a delay in facebook cache creation. The page created for datalet sharing implements all the FB directives. 
Anyway facebook provides this tools to check if page are conform to FB "crawler" : 

- https://developers.facebook.com/tools/debug/sharing/
- https://developers.facebook.com/tools/debug/sharing/batch/

**Comment by andrpet** [comment]
I used the datalet name as default title and the dataset domain as default description

**Comment by pinapalmieri** [comment]
Missing data (Title, description, Source ... )  in the landing page (below link) of a shared datalet on Facebook:
(@rended , @andrpet ):
http://spod.routetopa.eu/datalet/119

**Comment by andrpet** [comment]
Now in section with the datalet description we have added title and description (where available)
