### ISSUE TITLE
Publishing on facebook a datalet: better composition of the first part of the landing page

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#296]
The text part about the ROUTE-TO-PA project should be in a slighter smaller font and cleraly separated from the text "This barchart-datalet was created by....". So introduce some space.. 
If possible, get larger the image of the user that posted (top left) 
![image](https://user-images.githubusercontent.com/2544302/28490103-bf9df29a-6ed1-11e7-9dd9-442a775b50e3.png)

**Comment by andrpet** [comment]
Fixed
