### ISSUE TITLE
User Registration, no confirmation email

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#297]
"I was trying to login to Dutch SPOD, and it said that it was going to send me a confirmation link - but it still hasn´t arrived."

**Comment by lucavicidomini** [comment]
The SMTP account used for notifications was disabled. We replaced it with Elastic Email

**Comment by callmealien** [comment]
@lucavicidomini does this mean that new users will now receive email confirmations? What happens to the sign up from 8 days ago? Will they receive an email prompt, too?
