### ISSUE TITLE
Maplet: Empty Error Message

### ISSUE THREAD

**Issue by abirghattas** [routetopa/spod#311]
In Dublin Spod, when adding a maplet an empty error message appears if you select a dataset with no GIS coordinates. 
[Empty Error Message](https://lh6.googleusercontent.com/tcnyc1Hul4vDQynkFXxxoo7t_itBcHHRls0tOMmRBLaHyMO6CV09dwZoys6Y3S_bxTPkF9rje8bD6BI=w2552-h1360-rw "Empty Error Message")

**Comment by pinapalmieri** [comment]
Hi @abirghattas, 
could you provide us more details?


If you select a dataset with no GIS coordinate, a red notification suggests  the  datset is invalid. Please See  screenshot:
![image](https://user-images.githubusercontent.com/22379520/31828276-0ddd23fc-b5ba-11e7-842c-37670a2a318b.png)
