### ISSUE TITLE
Private space: preview of a map datalet is not shown

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#314]
When you add a datalet map into the private space, the datalet is correctly imported, but it is not shown as a "image preview" (see the preview of the "pizzerie"). When the datalet is shown full screen, it works.. 

![schermata 2017-10-30 alle 15 55 55](https://user-images.githubusercontent.com/2544302/32177772-63d37544-bd8b-11e7-80fc-575b4789c60e.png)

**Comment by rended** [comment]
Fixed

**Comment by andrpet** [comment]
Webshot does not support ECMAScript 6 construct (that we use in map datalet). We rewrote source code in a webshot compatible version.
