### ISSUE TITLE
Public room: suggested datasets are not shown in evidence

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#315]
When the room has suggested datasets, they are not shown when the controllet is used to create a datalet within the room. See, for example, the room on "Marcianise" for the Hetor website.. 
And it seems like the same happens also in the co-creation knowledge room for the "suggested" datasets.. 
![schermata 2017-10-30 alle 16 31 56](https://user-images.githubusercontent.com/2544302/32179708-6762539c-bd90-11e7-843b-a009f8121f4d.png)

**Comment by andrpet** [comment]
Fixed with @rended
