### ISSUE TITLE
Cocreation room: invite a user to a cocreation room  without real name 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#316]
Feedback from Utrecht, November 8th 2017

Add participants to an already created co-creation room
When I find a name and enter the name a small cross appears on the screen (see below) 1
![image](https://user-images.githubusercontent.com/22379520/32546831-a364adbc-c480-11e7-9865-8ea441a3c1aa.png)

(2) A user doesn't complete own profile ( without Real Name)

![image](https://user-images.githubusercontent.com/22379520/32547099-6027851e-c481-11e7-8d9b-491b487d919c.png)

**Comment by vitsca** [comment]
In all the other platforms, not having a name is never a practice. Users that don't want to write their name can use anything.
