### ISSUE TITLE
Insufficient operations for filtering

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#317]
The operation "begins with" should also have "does not begin with" .. as "ends with.." should have also "does not end with.." ... instead, you have only this (in the picture).. please add the inverted operations.. @rended 
![schermata 2017-11-09 alle 19 12 44](https://user-images.githubusercontent.com/2544302/32622295-b73e26d0-c582-11e7-9c73-71d50e6180ac.png)

**Comment by rended** [comment]
Added new filters "does not begin with" and "does not end with"
