### ISSUE TITLE
SPOD app mobile: comments in an agora notified with missing info

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#326]
ONLY when writing  a comment from a desktop version, the mobile is notified but with an empty informative text (only "Agora") appears

**Comment by vitsca** [comment]
replicable but only on my smartphone... see screenshot.. but on other smartphones (Pina's) it is shown with an empty line at the end, that may be the case for not showing anything to me. 
![screenshot_2017-11-23-19-23-34](https://user-images.githubusercontent.com/2544302/33185766-28723df2-d085-11e7-8c77-4695757b9109.png)

**Comment by luigser** [comment]
FIxed
