### ISSUE TITLE
Mail notification: change the signature (urgent!)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#332]
It should not contain Google+ link (it is not part of our social media presence and it appears empty). Moreover, remove the phone numbers (all), and the email address.. consider if we can add the administrator email, but only if it can be specified (and configured?) for each platform.. .otherwise, delete also the email address.. 

Please, push it on all the platform, before the 2.7 official release

**Comment by andrpet** [comment]
Google+ link removed. Added Youtube ROUTETOPA channel link. Contact info configurable by administrator through language setting panel by platform administrator
