### ISSUE TITLE
Exported datasets in SPOD do not include any reference to license

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#334]
exported dataset in SPOD do not include any reference to (open) license... it is usually not a good strategy.. as the datasets can be used to build datalets, that can be later exported to FB and, then, made visible (as observed for one of the Prato datasets)... so, I would say that in the "export to SPOD" part, the choice of the license is to be forced (maybe using a simple dropdown list, with the major ones... as this is only temporary.. and that the license is indicated (in the list?).. 
@donpir probably this should be also checked (if it exists) in the new process of publishing on a CKAN, as this is a recurrent mistake in publishing..

**Comment by vitsca** [comment]
insert in the json the field of the license used by the user. 
The user can select among the list of available licenses, as taken verbatim by CKAN

**Comment by rended** [comment]
Metadata-list-controllet updated, @donpir will finish the job!

**Comment by vitsca** [comment]
@donpir @rended what is the situation? if ok, then close it :-)

**Comment by vitsca** [comment]
boys! @rended @donpir.. how are we on this issue? :-)

**Comment by rended** [comment]
done

**Comment by donpir** [comment]
I reopen the issue because it needs to update also the "Publish on CKAN wizard" where the license is mandatary.

**Comment by donpir** [comment]
When publishing on CKAN from SPOD, now it includes the license specified in the metadata.

**Comment by donpir** [comment]
Done, now when publishing on CKAN there is also the license that is mandatory.
