### ISSUE TITLE
Ethersheet does not import CSV with one column

### ISSUE THREAD

**Issue by donpir** [routetopa/spod#337]
Seems that Ethersheet does not import a CSV with only one column

**Comment by vitsca** [comment]
to be done checking that (as excel does) in this case a separator is however present at the end of the first (and only) column

**Comment by donpir** [comment]
Creating a dataset with one column in Excel and exporting a CSV, it does not place the separator (i.e., ";") at the end of each row. The same is for Open Office Calc. In this way it is a CSV file without any separator inside.

Ethersheet needs the CSV with at least one separator. So the "Import" Wizard requires a CSV file with at least one separator.

**Comment by donpir** [comment]
DONE. The CSV file with one column must have the separator at the end of each row ";"
