### ISSUE TITLE
Map Datalet updates are not pushed (URGENT!)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#339]
On spod.routetopa.eu. Have a dataset with many rows, only the first 7 have geocoordinates set. Built a map datalet, that filters out the "not null" values in the geocoordinates columns. It works. Now, if I insert a new geo coordinate in a row that was previosly empty (the eight) the datalet is not updated. If I refresh the whole page it works. 
The same bug happens with a map WITHOUT filters... If I build a datalet without filters, the empty coordinates are not shown (ok, @rended good job!) but again, it is not updated when changed. 
Other datalets (tried with the bar chart in horizontal) are updated as soon I change a value ... it is important to change it before the meeting of friday

**Comment by luigser** [comment]
Problem fixed.
