### ISSUE TITLE
CKAN  v.2.3: data explorer does not show Grid view (special chars in the column name) 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#341]
In the CKAN ( http://ckan.routetopa.eu/) v.2.3 , the tab for "Grid View"  of "Data Explorer" doesn't show the grid of data as expected, when the csv uploaded file contains the column name with special chars (-, /, +)

![image](https://user-images.githubusercontent.com/22379520/33373775-bb938032-d503-11e7-8a4c-0057c1412e4c.png)

**Comment by vitsca** [comment]
to be checked if the bug is still present in the newest CKAN release, otherwise provide sanitization of the title string.
