### ISSUE TITLE
Notification e-mail in Cocreation : link "confirm to join" does not work

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#349]
notification e-mail  arrives when  a  user   invites him/her in a new Cocreation data room, the link "Confirm to join" of the email does not work.

(See below screenshot)

![image](https://user-images.githubusercontent.com/22379520/34719665-e641f996-f53b-11e7-9afc-b80afd03a6f5.png)

**Comment by luigser** [comment]
Fixed.
