### ISSUE TITLE
Ethersheet sorting does not work

### ISSUE THREAD

**Issue by rended** [routetopa/spod#35]

**Comment by vitsca** [comment]
Can you provide details, @rended ? :-)

**Comment by luigser** [comment]
Dear @rended, Ethersheet sorting features works well now as before. We added some enhancements : since we consider the first row as dataset header the sorting will exclude it.

**Comment by rended** [comment]
Very wall @luigser, maybe one day you will become a Project Managers like me!

**Comment by luigser** [comment]
I'm already the PM but I like to leave you dreaming ;)

**Comment by vitsca** [comment]
We have a team full of PMs 👍
