### ISSUE TITLE
Cocreation data room (Publish on CKAN): Information Error Message not handled properly

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#357]
In  the Cocreation data or media room, when a  publication of a dataset fails, the error message is not handled (see below screen shot)
![image](https://user-images.githubusercontent.com/22379520/35856993-fac1c63c-0b37-11e8-8b44-a736176d6cf1.png)

**Comment by donpir** [comment]
When the publication on CKAN fails, the system gets the error message and shows it.
