### ISSUE TITLE
Map datalet: the link to a picture sometimes does not work

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#359]
Sometimes, when in the ballon, a picture URL is selected, it is not shown in the ballon, but only the URL link is shown. Sometimes it does work.. not sure, but maybe the extension JPG (capitals) is not recognized as an image? 
@rended ask the Hetor team for examples of bad or good behaviour..

**Comment by rended** [comment]
Fixed, only the lower case extensions were recognized.
