### ISSUE TITLE
Whats'new: "Show only my friends' activities"

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#36]
On the left above (Open Wall), there is the possibility to filter comments and posts just for friends. This is not translated. 

Translation
Voir les activités de mes amis 

![image](https://cloud.githubusercontent.com/assets/22379520/19164562/bb751838-8c00-11e6-9cb0-45cb9b2a3a6b.png)

**Comment by lucavicidomini** [comment]
Issue resolved.
