### ISSUE TITLE
Richer datalets: timeline with more fields

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#360]
For the timeline datalet, it should be possible to add more fields on the visualization, possibly joined together if all strings. So, I should be able to insert more fields in the same "textarea" to be visualized in the timeline for a specific date.

**Comment by vitsca** [comment]
@rended .. I remember that the same issue could be applied also to other datalets.. do you remember which? :-)

**Comment by rended** [comment]
maybe media-slider-datalet

**Comment by vitsca** [comment]
yes!

**Comment by vitsca** [comment]
May I also add something, @rended ? It would be good to be able to "merge" several fields of the table into the limited visualizations.. as an example, the main info we show for each date, could be together an image, a title, the date itself, and other fields combined together. 
It could be also on the media slider as well.. so, not only the "bottom" part (the description of each photo/data) but also the "central", main info displayed could be the merging of several fields.. any idea on how to work on it?

**Comment by rended** [comment]
see #294
