### ISSUE TITLE
Controllet: step 2.. wrong labels

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#361]
In step 2, if the labels contains accented letters (like Città) they are not shown correctly (char encoding wrong)
![image](https://user-images.githubusercontent.com/2544302/36015807-67c01402-0d70-11e8-9223-522b20438467.png)

**Comment by vitsca** [comment]
on hetor, spod 2.8

**Comment by rended** [comment]
It is not a controller problem (which shows the character as it is in the dataset).
The problem occurs when the dataset is loaded from CSV on CKAN: à becomes Â as well as other "special" characters.

**Comment by vitsca** [comment]
ok... @donpir ?

**Comment by donpir** [comment]
It is a CKAN issue, and how the dataset has been uploaded.

**Comment by vitsca** [comment]
Ok... whom should I tag then ? :)

**Comment by vitsca** [comment]
CKAN plugin for character encoding? @lucavicidomini ?

**Comment by lucavicidomini** [comment]
It is some sort of game? I tag @luigser!

Enough jokes... about CKAN, no such setting or plugin exists: it is duty of the uploader to set the right encoding on the file.

I did some test and asked @luigser to add the BOM at the beginning of the exported CSV. **Now it's working and will be pushed on next release**. Many thanks to @rended for his psychological support :)
