### ISSUE TITLE
Datalet.. missing link back to the dataset for DKAN website

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#363]
For the dataset: http://www.confiscatibene.it/it/dataset/regione-campania-beni-confiscati/resource/7066e39e-e745-4c8f-903d-6b87612f72c0#{view-map:{lonField:!Lon,latField:!Lat}} 
when you create a datalet (it works! since it is DKAN) in the datalet, the link back to the dataset is NOT shown.. why? 
![image](https://user-images.githubusercontent.com/2544302/36315366-c65c6106-1337-11e8-9645-bcd5a18cdb9b.png)

**Comment by rended** [comment]
Using DCAK API is "impossible" to get resource url starting from data url: missing resource_show?id:"xxxx"  api.

Now, as solution, we show the dataUrl instead of resourceUrl.
