### ISSUE TITLE
Add tooltip for each Cocreation room 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#365]
(Feedback from Consiglio Regione Campania team, March 06 2018)
When there are much cocreated rooms  with  a long and similar  name, it is difficolt to identify a specific cocreated room.

![image](https://user-images.githubusercontent.com/22379520/37047554-93eacb62-216b-11e8-8cdc-d907543416b8.png)

**Comment by vitsca** [comment]
If that is very quick, could that be included into the 3.1? thanks.. .

**Comment by rended** [comment]
Done
