### ISSUE TITLE
Cocreation data: the publication of already existing dataset does not work

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#367]
When a dataset  must be updated on the CKAN portal,  in SPOD platform, the publication of a dataset existing already on the CKAN portal shows a warning (see screenshot below), suggesting to update the existing dataset on the CKAN, but this doesn't  work at all. CKAN stores the file in the "trash" folder, and  the solution is to remove the file from the  "trash" folder.
In the SPOD, modify the warning message, suggesting to remove directly the file from "trash" folder on the CKAN portal.  

![image](https://user-images.githubusercontent.com/22379520/37699556-59246b0e-2ce8-11e8-8ac6-cb142c2014d9.png)

**Comment by rended** [comment]
fixed
