### ISSUE TITLE
Maps in the Controllet: non visualization of teh map when some of field is null 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#370]
When a  "Musei di retrocompunting"  dataset (available here http://ckan.routetopa.eu:8080/dataset/41d6f3b7-1d43-4b6f-880a-bd3b12750085/resource/9d403265-f4a3-44ee-ae32-abc7a31f1498 ) shows some of the fields with "null" value, the map  is not shown  in the "What's new" page. (The same issue does not occur in the Agora)

(The screenshot below shows the map, selecting the fileds such as "All in One, Altri strumenti" and Position,)
![image](https://user-images.githubusercontent.com/22379520/41663761-7b1a93d8-74a4-11e8-92ae-6d0eed387d44.png)

The same map in the Agora works fine (see screenshot below)
![image](https://user-images.githubusercontent.com/22379520/41663898-c5be72f6-74a4-11e8-876d-13522e69e856.png)

Suggestion by @andrpet : to manage the "null" value in the fields of a dataset in the map of the Controllet.

**Comment by rended** [comment]
fixed
