### ISSUE TITLE
Room: 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#38]
On a room, while I want to add a datalet while I want to click the “my space” button, this is not translated space” button, this is not translated  

Translation “Ouvrir mon espace”

![image](https://cloud.githubusercontent.com/assets/22379520/19164434/3acbff8a-8c00-11e6-982f-7178e13c9684.png)

![image](https://cloud.githubusercontent.com/assets/22379520/19164447/498c397c-8c00-11e6-8a4a-1e0174bf76c9.png)

**Comment by andrpet** [comment]
Fixed
