### ISSUE TITLE
Migrate  from  HTTP to HTTPS 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#381]
When a website delivers HTTPS pages, all active mixed content (e.g,  embedding html code of datalet of SPOD to web page ) delivered via HTTP on this page, will be blocked by default,  
The  strategy to avoid mixed content blocking is to serve all mixed content as HTTPS instead of HTTP.
(Migrate SPOD, DEEP platforms from HTPP to HTTPS)

**Comment by rended** [comment]
done!
