### ISSUE TITLE
Controllet: same datasets and different visualization with bar and column charts when browser's zoom is not set to 100%

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#392]
In the Controllet, the "Alberi Monumentali" dataset (available at the link: http://ckan.routetopa.eu:8080/dataset/40311576-afd4-4d45-a7bf-d4cf2a630b7c/resource/e5acc3cc-06d0-4520-b1d7-fbf29da29c02) shows different visualization between  bar and column charts (see screenshots below).
![image](https://user-images.githubusercontent.com/22379520/47991818-8221f500-e0eb-11e8-830d-a9d3ea65b480.png)
i.e: 

In particular the zoom setting of the "Chrome" browser is 110% , the column char shows an heigh  different of the "platanus acerifolia" tree (the maximum height ofthis tree is 37 )  
![image](https://user-images.githubusercontent.com/22379520/47992031-20ae5600-e0ec-11e8-9178-126da3afa178.png)
(the colum chart works fine with  100% zoom setting of the  "Chrome" browser, see screenshot below
![image](https://user-images.githubusercontent.com/22379520/47992393-13de3200-e0ed-11e8-8e0f-ad6a51dfde92.png)

 )
Below the dataset: 
![image](https://user-images.githubusercontent.com/22379520/47991927-d036f880-e0eb-11e8-9376-4540c2635eaa.png)

**Comment by rended** [comment]
It's not a bug, just highstock approximations, we cannot do anything.
