### ISSUE TITLE
Post in Agora shows html text

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#4]
(SPOD 1.8, September 2016)
In a room, if a click on a circle of the “Comments graph” (right side), in the text HTML is shown (see image 3 in annex)

![image](https://cloud.githubusercontent.com/assets/22379520/18974318/946a4b72-86a2-11e6-9c9a-8e0c1a72e65a.png)

**Comment by pinapalmieri** [comment]
When copying and pasting , the pasted text displays HTML tags.

**Comment by rended** [comment]
Fixed
