### ISSUE TITLE
Reports of the Agora' comments are not grouped together

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#41]
The Agora' comments used to be grouped together in groups of 10 (or something).. I see (on the spod for the HETOR project) each comment appearing on the Agorà... it seems not working.. 
A comment: actually, I found it useful to spot newcomers entering in the rooms... should we discuss it? maybe reestablish grouping but provide some alternative mechanism to show newcomers..

**Comment by andrpet** [comment]
We can't reproduce the bug ... when I open an Agora Room the last 10 comments are shown, and page scrolls down to the last one. The comments are grouped by 10. 
Which browser have you used (all the Agora Rooms present the same problem ?).

**Comment by vitsca** [comment]
Sorry I was not clear: I was referring to the fact that the updates on the "What's new" does not appear to have the comments "grouped" i.e. only every 10 comments, one post is made that somebody did something.. I saw a single person commenting on a room...
