### ISSUE TITLE
Front page: shows Bacheca, Friends, Iscriviti on top bar

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#410]
.. although no authentication has been made.. they must be hidden... only authenticated users can see something of the content of the SPOD.. 

![Schermata 2019-03-26 alle 15 05 34](https://user-images.githubusercontent.com/2544302/55003406-ab7ae900-4fd8-11e9-8fb1-8713048144c0.png)

**Comment by lucavicidomini** [comment]
Done.
