### ISSUE TITLE
Cocreation: Quality Check button

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#411]
The Cocreation data room shows a new feature: the "Quality check" button.
Please @mariaangelapellegrino shows details

**Comment by mariaangelapellegrino** [comment]
By asking for the quality check, AT THE MOMENT, we look for _type inconsistencies_ and _completeness_.
More in detail, the quality check notifies:
- if a value is NULL by surrounding the cell by a red border (it represents the _completeness_);
- if a column contains more than one datatype (also NULL is considered a datatype), a warning is put on the column header to report _type inconsistencies_;
- a report of all the _type inconsistencies_ is presented on the table name.
