### ISSUE TITLE
Page of HELP on Regione Campania

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#416]
- Place first the material in italian, with updates.. then the english (Pina)
- We will place the small videos we will register.. make room for a section of "Online training" now empty (Pina)
- create a alias mailing list (Luca) on routetopa that is rc-support@routetopa.eu with Luca, Vittorio, Pina (then we will also place RC people from Open Data Team), at least, and use it as the support mail address in the page

**Comment by vitsca** [comment]
- (Pina) SPOD Helper (the question mark on top right) is only on datalet, please write something more before, with the indication of the (1) left bar, (2) top bar, (3) to right buttons

**Comment by lucavicidomini** [comment]
Mailing list is done

**Comment by pinapalmieri** [comment]
"Help" page done, adding a quick Italian help, and updated e-mails (Team and Accademia Open Data ) 
SPOD Helper done for "Novità" page!
