### ISSUE TITLE
WRONG MAP... coordinates?

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#417]
see the Novità on the RC site... the centri per l'impiego in Azerbaijan ... ???

<img width="614" alt="Schermata 2019-03-29 alle 07 27 37" src="https://user-images.githubusercontent.com/2544302/55213672-4ef41580-51f4-11e9-9c94-71f4d2dda8d8.png">

**Comment by andrpet** [comment]
Wrongs coordinates as input
