### ISSUE TITLE
URGENT: Export as CSV does not work... 

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#421]
it remains hanging .. and then error 502 ... 
the url used is 
http://iteropendata-crea.regione.campania.it/ethersheet/export/s/981410d5-24a3-415a-aec3-30708c037b6a.csv
![Schermata 2019-03-29 alle 13 58 21](https://user-images.githubusercontent.com/2544302/55234154-c6dd3280-522a-11e9-9623-447aee920845.png)

**Comment by lucavicidomini** [comment]
@andrpet put the service down few minutes ago as he's working on it.

**Comment by andrpet** [comment]
Fixed (refactoring refreshConnection in ethersheet_service.js in order to take socket file from config file)
