### ISSUE TITLE
(URGENT Monday morning) Cocreation data: the Sidemenu (on the left side) disappears by selecting it

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#422]
In the cocreation data room (http://iteropendata-crea.regione.campania.it/) the SideMenu disappears by selecting it.
![image](https://user-images.githubusercontent.com/22379520/55288019-8fe55900-53b1-11e9-8de9-c97b40f12c6b.png)

**Comment by andrpet** [comment]
Explain how to reproduce the bug

**Comment by luigser** [comment]
This bug arise every time the user click on menu button

**Comment by luigser** [comment]
It depends on browser window size. If it's in a fullscreen mode the bugs seems not to occur
