### ISSUE TITLE
Cocreation data: " split screen" doesn't work correctly

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#423]
In the Cocreation room: the "Split screen "feature" doesn't work ; it works with "refresh" .

Here the Cocreation Room with the "Split screen"
![image](https://user-images.githubusercontent.com/22379520/55353851-91537600-54c4-11e9-9d84-078dda164b89.png)

The whole page, clicking on the "Split screen":
(1)
![image](https://user-images.githubusercontent.com/22379520/55353923-b6e07f80-54c4-11e9-9593-5315a0dde091.png)

(2)
![image](https://user-images.githubusercontent.com/22379520/55353948-c6f85f00-54c4-11e9-91fe-869698ff24ac.png)

(3) Reload the page
![image](https://user-images.githubusercontent.com/22379520/55353988-e099a680-54c4-11e9-8be0-8009965f2867.png)

**Comment by luigser** [comment]
fixed
