### ISSUE TITLE
"Open Campania Crea" platform: change Site Name

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#424]
(1) In the "Open Campania Crea" platfrom change, in the basic configuration name, configure "Site name".
(i.e. SPOD should become "Open Campania Crea")
![image](https://user-images.githubusercontent.com/22379520/55493542-6d657100-5639-11e9-8051-9726c3e30121.png)

- Customize the Site name (i.e.  {$siteURL}).

**Comment by vitsca** [comment]
still not working. in the mail I receive there is the button "Vai a SPOD" .. 

![image](https://user-images.githubusercontent.com/2544302/55953580-c007e400-5c5c-11e9-9dfa-ba7387ca5eec.png)
