### ISSUE TITLE
Map datalets get zoomed out automatically

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#43]
`Utrecht,  SPOD (v.1.8) , September 26 2016`

In general, the new page you get to see when you login is very promising. It is a better overview of what you can do, I particularly like the Spod Help button. A lot more user friendly as before. One small thing about  the What’s new page is when a datalet is created with geographical coördinations it shows up on the What’s new page let’s call it ‘interactive’. When you scroll with your mouse to go down on the page, map datalets get zoomed out automatically. Maybe it would be possible to ‘lock’ the maps so you online zoom out or in when you click on the + or – sign of the datalet. See screenshot  below:

![image](https://cloud.githubusercontent.com/assets/22379520/19223831/98da7bd0-8e79-11e6-9d3c-52e240542335.png)

![image](https://cloud.githubusercontent.com/assets/22379520/19223833/9e44193c-8e79-11e6-9410-06a70af787c1.png)

**Comment by andrpet** [comment]
This is the default behavior of all the maps (leafletjs, google maps ecc ecc)
