### ISSUE TITLE
Datalet: "Click to Copy HTML" feature must embed  cached data

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#434]
The "Click to Copy HTML" feature of the datalet must embed cached data exporting a datalet 

![image](https://user-images.githubusercontent.com/22379520/55613336-c2fd6300-578a-11e9-8e84-a066f61a3e55.png)

**Comment by vitsca** [comment]
There should be' TWO modes. 
1.  Copy HTML with cached data
2. Copy HTML with live data

**Comment by rended** [comment]
- Copy HTML copia SEMPRE anche la cache.
- Le datalet fuori SPOD non usano MAI la cache (anche se come detto prima ce l'hanno).
- Se per qualche motivo non si riescono ad utilizzare i dati live (non sono più presenti, problemi di connessione, sono cambiati in maniera incompatibile con la visualizzazione) si scala alla cache.
- In qualsiasi momento cliccando sul pulsante si può passare dai dati live ai cached e viceversa.
