### ISSUE TITLE
Add more info about the users (e.g. data analist, student, journalist) 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#44]
`(Utrecht, SPOD (v.1.8) , September 26 2016)`

The members page is a good feature and with the new interface it also looks nice. However, it would be good if you can see what the person’s background is (e.g. data analist, student, journalist) and where they are from and what topic they are interested in. This way you could connect more easy with people you should be in contact with for your project. See screenshot below

![image](https://cloud.githubusercontent.com/assets/22379520/19223879/91cc089e-8e7a-11e6-8ad3-14d9b3e33fcf.png)
Add more info about the users. For example Gianluco De Martino (Italy/Data-Analist/ Circular Economy) or something like that.

**Comment by vitsca** [comment]
Moved to the UX&UI project..

**Comment by rended** [comment]
We decided according with project partners / users to not show personal informations for privacy reasons.
