### ISSUE TITLE
Add Tag for Dataset in Step1)

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#45]
`Utrecht, SPOD (v.1.8) , September 26 2016`

When selecting a dataset it is a good thing that you can now select the provider or incorporate a dataset that has been cocreated. However, this is not clarifying enough yet for users with relatively low knowledge. It would be an improvement if there were tags on which you could search like in TET for example. 

![image](https://cloud.githubusercontent.com/assets/22379520/19223932/398dfbd2-8e7b-11e6-95be-a79d98e5251c.png)

**Comment by andrpet** [comment]
Not all datasets provider has or provide TAG for the datasets. Moreover the TAG and TAG rules are not handled by SPOD .
