### ISSUE TITLE
URGENT: bug in the authoring page in the deep2

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#459]
When using the deep2, authoring "controllet" (accessed via the 
http://deep.routetopa.eu/deep2/COMPONENTS/creator_from.html?ln=it&data-url=http://test.dati.regione.campania.it/ckan/api/3/action/datastore_search?resource_id=f9a6ff2a-e5f5-48e0-887e-e2bcfbe67d81%26limit=99999

for example) ... it is not possible to insert "(" in the small textbox for the logical expressions of filters.. I had the impression that they are inserted but are not shown ..

**Comment by vitsca** [comment]
Confirmed: the '(' are correctly place but not shown .. see also #460 for visibility of the textboxes..

**Comment by rended** [comment]
fixed
