### ISSUE TITLE
Datalet: Histogram shows date indicator in the zoomable area

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#465]
The histogram chart shows zoomable  area with date indicator  on the x-axis.
Here the dataset address (http://test.dati.regione.campania.it/catalogo/datasetdetail/alberi-monumentali-della-campania)

See screensht below:
![image](https://user-images.githubusercontent.com/22379520/56128475-01abce00-5f80-11e9-84b5-69f173ad76bd.png)

**Comment by rended** [comment]
fixed
