### ISSUE TITLE
Select  a dataset from the Dutch government but only got numbers as names: not clear

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#47]
`Utrecht, SPOD (v.1.6) , 11th July 2016`

In wanted to make a datalet in the co-creation room and select  a dataset from the Dutch government but only got numbers as names, see figure below.  therefore it is completely unclear what the datasets are about

![image](https://cloud.githubusercontent.com/assets/22379520/19224135/02495e0a-8e80-11e6-8e57-b4e4ad010b55.png)

**Comment by vitsca** [comment]
they should provide the url of the dataset so that we can check.
Most probably the dataset may contain data that has no "names" .. 
Moreover, It is not clear why the image submitted should help us...

**Comment by rended** [comment]
The name shown is the "Resource Name" and we haven't control on it. Obviously the dataset creator chooses it. The metadata shown on the right (most of them optional) can help to understand what the datasets are about. Moreover the extended search works on metadata and on content of the dataset so is more easy find dataset of interest.
