### ISSUE TITLE
Problem adding a new comment in Agora

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#48]
`Utrecht, SPOD (v.1.6) , 11th July 2016`

I wanted to add a new comment in the Agora of Groningen and opened my own datalet made earlier. I wanted to make a comment but could not add the comment because the  datalet took up the whole screen and it was not possible to scroll down. After some time I was finally able to add a comment

**Comment by vitsca** [comment]
Can we have more information about the kind of computer (screen size), the screen resolution (if it is extremely low, then we can have problems, we require a minimal resolution for desktop .. I recall 1366 x 768 or even higher)...

**Comment by andrpet** [comment]
Fixed
