### ISSUE TITLE
Highlight the added rows

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#51]
`Utrecht, SPOD (v.1.6) , 11th July 2016`

I have added rows in an existing cocreation room but it is not visible that I have added these rows. I think it is important for the creator of the room who adds data

**Comment by andrpet** [comment]
Maybe the row level it's not enough, because different users can modify the same row. It's more convenient to work on the single cell.

**Comment by rended** [comment]
This feature is really difficult to implement and probably would generate a very confused UI with many colors that can not be easly and immediately interpreted (the same row/cell can be modified by several user within a few seconds or even at the same time).
