### ISSUE TITLE
 Website slow

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#52]
Groningen: feedbacks from students at Utrecht University (SPOD (v 1.4),  30-6-2016) 

Loading the website is terribly slow. In order to be able to work with it you have to open several tabs to be able to switch between Agora and Co-Creation. If you do it within one tab it is way too slow.

**Comment by vitsca** [comment]
Can we ask for more information about: 
- bandwidth available (type of the connection on the internet, wired/wireless etc)
- computational power of the computer (CPU, RAM..)
- type of browser used
- any other contextual information that may be useful (was another program running?)

**Comment by andrpet** [comment]
From 1.4 ver there are several interventions on SPOD performances. Maybe is convenient to replicate the test on 1.9 ver.

**Comment by vitsca** [comment]
Ok. Let's give it close, with further exploration in the same situation (and if it occurs again, please, ask for more info as described above)..
