### ISSUE TITLE
Missing enter button and not allow to write extensive messages in the Agora. 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#54]
Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4),  30-6-2016) 

In Agora it is not possible to use Enter when writing messages, which hinders the users. You cannot write extensive messages in the Agora. 
Similar the moderator of the challenge noted: They get cut of and can’t be seen by the others. This is annoying, because sometimes you want to add certain background information about your datalet

**Comment by andrpet** [comment]
Both issues are been resolved since 1.8 ver
