### ISSUE TITLE
Add  a statement  waiting the loading of a dataset too big

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#56]
Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4),  30-6-2016) 

Loading a dataset can take minutes without anything happening. It seems to the student that the file may be too big, but this should be depicted in the tool. A statement saying this dataset is too big. Now you are just waiting and do not know what is happening.

**Comment by andrpet** [comment]
The loading mechanism is improved and a loader was added to the Controllet.
