### ISSUE TITLE
 A lot of datasets that have nothing to do with the Groningen Project

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#57]
Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4),  30-6-2016) 

It is really hard to work with the datasets, because all the datasets are randomly descripted in a very long list. There are a lot of datasets that have nothing to do with the Groningen Project

**Comment by andrpet** [comment]
Dataset listed in the Controllet are configurable by the SPOD administrator. We made numbers of  improvements to the controllet layout since the 1.4 ver.
