### ISSUE TITLE
User profile: it is only possible to fill out your age until the year 1992

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#60]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

When registering it is only possible to fill out your age until the year 1992, after that it is not possible anymore. It seems practical to have a bigger marge. We had to lie about our age because we are younger.

**Comment by vitsca** [comment]
Yes.. we will change it .. we also want young people in SPOD! :-)

**Comment by pinapalmieri** [comment]
A new Year range (from 1920-2000) for Birthday for User profile has been set up on SPOD.
Administrator Guide, SPOD “Nash” (1.9)(Draft, version 2.0, 10/18/2016) describes how change  User profile (see “Profile Question” section)
