### ISSUE TITLE
Two charts with the same dataset

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#61]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

It is important to be able to use two lines in the same graph in SPOD. Students struggled to use this, and otherwise you have to make a new datalet for every variable. This is crucial for SPOD to be workable

**Comment by vitsca** [comment]
More details have to be asked @pinapalmieri ... I think we already multi series graphs inserted, maybe in 1.4 they were not available. Please ask the submitter of the report to check whether it is solved. IN that case, you can close the comment, thanks @pinapalmieri

**Comment by pinapalmieri** [comment]
Groningen confirms that  the multi series graphs available in the new version of SPOD (v. 1.9) have resolved the highlighted issue.
