### ISSUE TITLE
User profile more personal

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#63]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

It could be made more personal. Now you only have to fill out your age and your name. Possibly this could be enhanced with a small profile where you have a picture and short text about yourself, including your qualifications (e.g. public administrator, data specialist, etc.)

**Comment by andrpet** [comment]
The profile information can be handled by the SPOD Platform Administrator
