### ISSUE TITLE
Upload an image:  symbol is misleading,

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#64]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

Small detail for Agora: when uploading a file you have to click on the ‘photocamera’ next to where you fill out your comment. This symbol is misleading, says one of the students. They first press the first sign instead of the photocamera.

**Comment by rended** [comment]
I'm sorry for the student, but for the rest of the world the camera symbol refers to "upload a picture". Now is not possible upload other type of files. maybe the first icon (folder +) is misleading: it refers to "import from my space" and not "upload a file", if you have suggestion we could change it.
