### ISSUE TITLE
To group messages on topics or discussions. 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#65]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

Agora is not really well structured according to the students. It might be practical to group messages on topics or discussions. Now you have to search too far back to see what people said.  Furthermore, process and substantial questions are now asked intertwined – there is no structure in the Agora

**Comment by vitsca** [comment]
It is an important comment.. we would like to deal with this in the refactoring of the Agorà, to provide more hints on the structure, or change the structure (although we will not revolutionize the interface and the approach). Moved into the Agora refactoring project

**Comment by rended** [comment]
We moved to new Agora.
