### ISSUE TITLE
Different channels within Agora

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#67]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

It would  be any idea to create different channels within Agora, one where you are with everybody and one with for example only your group

**Comment by vitsca** [comment]
The issue should be discussed with the researchers: of course this is not only a technical point, but it requires some thoughts about the kind of discussions and collaboration we want to achieve in the Agorà. 
Anyway, there is already the Data Co-creation room, where a discussion (similar to agora) can be held for a small group by invitation. And it can be used for small groups interactions, if needed.
