### ISSUE TITLE
Add "To do list "

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#71]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

A To do list might be helpful when working in the cocreation room with several others. Then you can see who is doing what and you can indicate when you are finished with your job.

**Comment by luigser** [comment]
I think this could be done directly in one of the documents in the room (_ideas_ f.i.). Are you thinking to add a new tab with new document(_to do_) or to provide new component?

**Comment by vitsca** [comment]
I think that @luigser is right (about the knowledge).. but I still see the comment valid for the data co-creation.. in that way, one could synchronize with others.. I would not place it in high priority (as we had only one report of that) ..

**Comment by rended** [comment]
This feedback refer to a really old version of SPOD (1.4), now users can synchronously communicate through new discussion tool, etherpad document inside the room and the oxwall chat. Moreover the user can switch panels more easily using the new split mechanism. Adding a fourth (or fifth if we consider ethersheet) tool to collaborate/communicate could create confusion and worsen the user experience.
