### ISSUE TITLE
Unclear how to move the datalet from MySpace to Agora

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#72]
(Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016) )

For one of the students it was unclear how to move the datalet from MySpace to Agora. Now she created a new one in Agorà. Although we explained it, apparently it was not clear enough for the students.

**Comment by rended** [comment]
Add a datalet in My Space is very simple:
   1 - click My Space button (foloder icon)
   2 - choose the datalet you want to add from the pop-up window
![add2](https://cloud.githubusercontent.com/assets/17746902/20387175/30d902b8-acbf-11e6-84de-842923d1de92.png)
