### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by vinsan** [routetopa/spod#73]
In the installation guide the ubuntu-14.04.5-server-amd64 version is indicated as preferred. It's mandatory  this particular version ?

**Comment by andrpet** [comment]
The last version of ubuntu come with the last version of PHP. As pointed out in the OXWALL forum [here](https://developers.oxwall.com/forum/topic/41415) and [here](https://developers.oxwall.com/forum/topic/47561) OXWALL is not ready and fully tested for PHP7. So ...  ubuntu-14.04.5-server-amd64 it's not mandatory but highly recommended for a quick deploy of OXWALL and SPOD
