### ISSUE TITLE
[Controllet]Search bar position 

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#75]
Search bar in ‘Select Dataset’ step of the datalet creation process is not obviously placed on the page. It takes a new user a while to figure out it's placement. Perhaps move it to the top right section, next to the provider drop down?

**Comment by rended** [comment]
Good suggestion, we'll take in account for next releases.

**Comment by callmealien** [comment]
Ace, thanks @rended.

**Comment by vitsca** [comment]
Moved into the project UX & UI Backlog.. thanks Sera

**Comment by rended** [comment]
In the end we decided to leave the search bar position on the bottom for consistency with the other steps of the controllet.
