### ISSUE TITLE
[Controllet][Enhancement]Save dataset drafts

### ISSUE THREAD

**Issue by callmealien** [routetopa/spod#76]
It is not currently possible for users to save dataviz-creation sessions mid-way, exit the platform and get back to it at a later time. Whatever is not saved is lost. Possible to allow for drafts to be saved, even if for a limited amount of time?

**Comment by rended** [comment]
Add this feature would require a great effort and (development) time, but is possible to save visualization in _My Space_ (private space) then **modify it** (whenever you want) before post it. When a visualization is opened in modify-mode all parameters/options (filters, group by, theme, title etc...) are loaded.
