### ISSUE TITLE
[Wishlist] Dataset Title Translations

### ISSUE THREAD

**Issue by serahrono** [routetopa/spod#77]
In the controller, datasets from different sources are in different languages depending on the source, rightly so. Suggestion: if user selects language x when they log into SPOD, have dataset titles, at least, translated into language x, too.

**Comment by rended** [comment]
The only way to do this is an automatic translation (that we never use in SPOD) and the results would be probably worse than let it in native language. Moreover all the metadata and the content of the datasets would remain untranslated.

**Comment by callmealien** [comment]
Makes sense @rended, at least for now. Was thinking of a use case- say an French-speaking user intending to learn something about Italy from the data available on SPOD when we open it up to the public. We can think of how to implement this in the long run, towards the end of the project for the benefit of communities using ROUTETOPA tools
