### ISSUE TITLE
Comment field has a couple of icons blocking the view of the user from seeing the comment 

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#78]
Agora: The comment field has a couple of icons blocking the view of the user from seeing the comment he/she is typing on the comment field. It would be nice to push these icons away from the comment field.

**Comment by vitsca** [comment]
Very necessary... moved into the project UX & UI

**Comment by pinapalmieri** [comment]
Icon doesn't block the commnet fileds.
![image](https://cloud.githubusercontent.com/assets/22379520/19486110/923600ac-955d-11e6-861f-b33384d51b4e.png)
