### ISSUE TITLE
Other Open Data  Protocol: ODATA protocol

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#79]
Groningen: Feedbacks from students at Utrecht University (SPOD (v 1.4), 30-6-2016)

It simply is unsuccessful for the students to analyse datasets via SPOD. The tool does not show anything when trying to use a dataset. (This is about big datasets the students uses from other websites like CBS).

**Comment by rended** [comment]
@pinapalmieri @vitsca We need more information about this issue. Otherwise we should close it.

**Comment by vitsca** [comment]
Ok.. probably it was a very early version of SPOD:. and it has been overtaken by the favourable feedback about the tool .. so, we close it
