### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by lucavicidomini** [routetopa/spod#82]
A proxy would help with the following issues:
1. Missing Accept-Origin header
2. Simpler access to CSV files
3. Support for different file types (transcoding)
4. Zip files (also for [Google Traffic data](https://developers.google.com/transit/gtfs/))

**Comment by lucavicidomini** [comment]
Time to start discussion about this issue, @vitsca @andrpet @luigser @rended @donpir ...

**NodeJS** :vs: **PHP**

what would we choose?

**Comment by vitsca** [comment]
I am old style.. I vote for PHP: ..

**Comment by andrpet** [comment]
... at last we choose Nginx as proxy
