### ISSUE TITLE
SPOD internationalisation - missing translations

### ISSUE THREAD

**Issue by arekstasiewicz** [routetopa/spod#84]
It seems that the translations for some of the messages are not working properly.

![error_1](https://cloud.githubusercontent.com/assets/2188771/19484662/3b5db408-9550-11e6-99a7-bfe291325ee7.png)

![error_2](https://cloud.githubusercontent.com/assets/2188771/19484666/3df2406c-9550-11e6-8048-77705ed3eea9.png)

**Comment by pinapalmieri** [comment]
Updated the language file for public room

![image](https://cloud.githubusercontent.com/assets/22379520/19485722/36460d38-955c-11e6-8481-cd2c3978fdc9.png)
![image](https://cloud.githubusercontent.com/assets/22379520/19485920/cfdaca56-955c-11e6-8c20-32117b7663ad.png)
