### ISSUE TITLE
Error in internazionalization (in italian!) on the What's new!

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#85]
Here is the mistake.. it should be "suo stato" not "loro stato
![schermata 2016-10-18 alle 23 16 07](https://cloud.githubusercontent.com/assets/2544302/19496720/1275e856-9589-11e6-8e46-880278927c1d.png)
"

**Comment by pinapalmieri** [comment]
![image](https://cloud.githubusercontent.com/assets/22379520/19510530/f4de7cc6-95e3-11e6-9777-9270aaa2a79d.png)
