### ISSUE TITLE
Blog-like feature is needed

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#88]
A "blog"-like feature is needed with the following characteristics:
- it should be writable only by moderators, but readable by everybody (public, no login required)
- it should allow to write nicely rich text
- it should allow to insert datalets (from scratch or from myspace)
- it should be a plugin so that it can be turned off if required
- it should allow voting and listing the most popular posts

Usage: 
- it can be used for letting out some progress on the work currently being done in SPOD.. a page with a static URL to link to, to export elsewhere, to tweet about, etc.

**Comment by pinapalmieri** [comment]
A basic editor is available for Blog with following features:
 - allows to insert datalet 
- it can be be turned off if required
- it can be writable only by moderator
- it allows votings only registered users
