### ISSUE TITLE
[new feature] E-mail notifications

### ISSUE THREAD

**Issue by lucavicidomini** [routetopa/spod#89]
**Please contribute, i will keep this post updated.**

A list of possible email events.
- Agora
  - Somebody post a message in an Agora I am partecipating in
  - Somebody replies to a message
  - Somebody imports a datalet into his Space
- CoCreation
  - Somebody invites me
  - Somebody writes in chat
  - Somebody creates a datalet
  - Somebody updates the datataset
    - not _every_ update, it could send an email once per room if there are updates since my last visit
  - Somebody publishes the dataset

**Comment by pinapalmieri** [comment]
#155

**Comment by luigser** [comment]
We will provide a new feature for email notification for all SPOD plugins
