### ISSUE TITLE
Adding a member in the cocreation: UI bug (Urgent)

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#90]
When adding a NEW member into the cocreation, if I type one letter, a long list appears, but if the user I want to add lies (in the drop down list) outside the popup window of the "add new user" then the click is taken to exit from the "add new user" and I am bounced back.. also the focus of the "add new user" is wrong with the other window (the one that appears when you press the (I) on the left). The "add new user" is behind the old window.

Possibly the new polymer or new chrome?

**Comment by luigser** [comment]
The "Add new user" form was refactored to resolve this issue.
