### ISSUE TITLE
Open Wall: enrich homepage with useful information, contacts for citizens

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#92]
(Prato meeting,  October 20, 2016)
Open Wall: enrich with new information:
-	Video link (Tutorial #1: Una rapida introduzione)
-	Help link as:
“Chi posso contattare se ho bisogno di aiuto?
Per qualsiasi necessità puoi scrivere una mail webmaster-prato@routetopa.eu (create a new mailing list include  Paolo, Elena, Diletta, Pina)
-	Link manual (englisg version) 

 (@lucavicidomini)  Create a new mailing list webmaster-prato@routetopa.eu

**Comment by lucavicidomini** [comment]
The mailing list was created and set as recipient address for the "Feedback" page. You can close the issue when the other items of the list are done.
