### ISSUE TITLE
Update Whats’new (widgets)

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#93]
Prato meeting,  October 20, 2016

Whats’new
-   New widget (“Chi posso contattare se ho bisogno di aiuto?
  Per qualsiasi necessità puoi scrivere una mail webmaster-prato@routetopa.eu)
-   (Update) Benvenuto in SPOD! Alcuni link per iniziare a conoscere SPOD:
  o   Tutti i video
  o   Una rapida introduzione in SPOD
  o   Video per Agora
  o   Video Controllet
  o   Video Cocreation data

**Comment by luigser** [comment]
Done.
