### ISSUE TITLE
After Login, update link  "Go to TET"

### ISSUE THREAD

**Issue by pinapalmieri** [routetopa/spod#94]
(Prato meeting,  October 20, 2016)

After login (http://prato.routetopa.eu/openid/),  "Go to TET"

Link verso TET (Go TET)? (Check)
TET 2.0        http://prato-tet.routetopa.eu
CKAN           http://prato-tet.routetopa.eu:8080
TET 1.0        http://prato-tet.routetopa.eu:8081

**Comment by lucavicidomini** [comment]
Do they need links to both TET 1.0 and TET 2.0 or just the latter? @pinapalmieri
